### ISSUE TITLE
No easy way to run tests in a simulator from the build script.

### ISSUE THREAD

**Issue by jasiek** [intel/intel-sgx-ssl#10]
There should be a SGX_MODE passthrough from the build script to each of the makefiles which build TestApp - that way, it will be possible to build and run tests on a simulator on a CI/CD machine.

**Comment by akryeem-INTC** [comment]
Will add a SGX_MODE flag with possible values of {HW, SIM}, to build in simulation mode call build script with SGX_MODE=SIM.

**Comment by akryeem-INTC** [comment]
This improvement was recently added.
Build test app with `make SGX_MODE=SIM`, and run it.
