### ISSUE TITLE
undefined reference to pthread_rwlock_init 

### ISSUE THREAD

**Issue by essencejay** [intel/intel-sgx-ssl#103]
os: wsl2 ubuntu20.04
intel-sgx-ssl: lin_2.10_1.1.1g
openssl: openssl-1.1.1g.tar.gz

errors:
error:
[ 62%] Built target tpdo-crypto
make[5]: Entering directory '/root/gopath/src/github.com/hyperledger/fabric-private-chaincode/common/crypto/_build'
Scanning dependencies of target TestEnclave
make[5]: Leaving directory '/root/gopath/src/github.com/hyperledger/fabric-private-chaincode/common/crypto/_build'
make[5]: Entering directory '/root/gopath/src/github.com/hyperledger/fabric-private-chaincode/common/crypto/_build'
[ 63%] Building CXX object pdo/common/tests/crypto/trusted/enclave/CMakeFiles/TestEnclave.dir///testCrypto.cpp.o
[ 65%] Linking CXX shared library ../../../../../../tests/libTestEnclave.so
/usr/local/bin/ld: /opt/intel/sgxssl/lib64/libsgx_tsgxssl_crypto.a(threads_pthread.o): in function CRYPTO_THREAD_lock_new': threads_pthread.c:(.text+0x4a): undefined reference to pthread_rwlock_init'
/usr/local/bin/ld: /opt/intel/sgxssl/lib64/libsgx_tsgxssl_crypto.a(threads_pthread.o): in function CRYPTO_THREAD_read_lock': threads_pthread.c:(.text+0x89): undefined reference to pthread_rwlock_rdlock'
/usr/local/bin/ld: /opt/intel/sgxssl/lib64/libsgx_tsgxssl_crypto.a(threads_pthread.o): in function CRYPTO_THREAD_write_lock': threads_pthread.c:(.text+0xa9): undefined reference to pthread_rwlock_wrlock'
/usr/local/bin/ld: /opt/intel/sgxssl/lib64/libsgx_tsgxssl_crypto.a(threads_pthread.o): in function CRYPTO_THREAD_unlock': threads_pthread.c:(.text+0xc9): undefined reference to pthread_rwlock_unlock'
/usr/local/bin/ld: /opt/intel/sgxssl/lib64/libsgx_tsgxssl_crypto.a(threads_pthread.o): in function CRYPTO_THREAD_lock_free': threads_pthread.c:(.text+0xee): undefined reference to pthread_rwlock_destroy'
/usr/local/bin/ld: /opt/intel/sgxssl/lib64/libsgx_tsgxssl_crypto.a(threads_pthread.o): in function CRYPTO_THREAD_init_local': threads_pthread.c:(.text+0x149): undefined reference to pthread_key_create'
/usr/local/bin/ld: /opt/intel/sgxssl/lib64/libsgx_tsgxssl_crypto.a(threads_pthread.o): in function CRYPTO_THREAD_set_local': threads_pthread.c:(.text+0x17b): undefined reference to pthread_setspecific'
/usr/local/bin/ld: /opt/intel/sgxssl/lib64/libsgx_tsgxssl_crypto.a(threads_pthread.o): in function CRYPTO_THREAD_cleanup_local': threads_pthread.c:(.text+0x19b): undefined reference to pthread_key_delete'
/usr/local/bin/ld: /opt/intel/sgxssl/lib64/libsgx_tsgxssl_crypto.a(threads_pthread.o): in function CRYPTO_THREAD_get_local': threads_pthread.c:(.text+0x167): undefined reference to pthread_getspecific'
/usr/local/bin/ld: /opt/intel/sgxssl/lib64/libsgx_tsgxssl_crypto.a(threads_pthread.o): in function CRYPTO_THREAD_get_current_id': threads_pthread.c:(.text+0x1b5): undefined reference to pthread_self'
/usr/local/bin/ld: /opt/intel/sgxssl/lib64/libsgx_tsgxssl_crypto.a(threads_pthread.o): in function CRYPTO_THREAD_compare_id': threads_pthread.c:(.text+0x1c5): undefined reference to pthread_equal'
collect2: error: ld returned 1 exit status
make[5]: *** [pdo/common/tests/crypto/trusted/enclave/CMakeFiles/TestEnclave.dir/build.make:123: tests/libTestEnclave.so] Error 1
make[5]: Leaving directory '/root/gopath/src/github.com/hyperledger/fabric-private-chaincode/common/crypto/_build'
make[4]: *** [CMakeFiles/Makefile2:379: pdo/common/tests/crypto/trusted/enclave/CMakeFiles/TestEnclave.dir/all] Error 2
make[4]: Leaving directory '/root/gopath/src/github.com/hyperledger/fabric-private-chaincode/common/crypto/_build'
make[3]: *** [Makefile:95: all] Error 2
make[3]: Leaving directory '/root/gopath/src/github.com/hyperledger/fabric-private-chaincode/common/crypto/_build'
make[2]: *** [Makefile:22: build] Error 2
make[2]: Leaving directory '/root/gopath/src/github.com/hyperledger/fabric-private-chaincode/common/crypto'
make[1]: *** [Makefile:11: build] Error 2
make[1]: Leaving directory '/root/gopath/src/github.com/hyperledger/fabric-private-chaincode/common'
make: *** [Makefile:22: build] Error 2

**Comment by jinghe-INTC** [comment]
It is recommended to take the latest SGX SDK and SGX SSL for your project. Please use:

SGX SDK: Linux 2.15
intel-sgx-ssl: lin_2.14_1.1.1k
openssl: openssl-1.1.1k.tar.gz (or openssl-1.1.1l.tar.gz)

If you have to keep the current versions, please tell me which SGX SDK it is, by executing:
`strings $SGX_SDK/lib64/libsgx_trts.a   | grep VERSION`
