### ISSUE TITLE
Appendix A Missing in PDF

### ISSUE THREAD

**Issue by xanderdunn** [intel/intel-sgx-ssl#114]
The [PDF](https://github.com/intel/intel-sgx-ssl/blob/master/Intel(R)%20Software%20Guard%20Extensions%20SSL%20Library%20Architecture.pdf) says "See Appendix A for the supported OpenSSL APIs.", but I don't see any appendices.

**Comment by jinghe-INTC** [comment]
You are right. The `Appendix A` is actually in the developer guide [for Linux](https://github.com/intel/intel-sgx-ssl/blob/master/Linux/package/docs/Intel(R)%20Software%20Guard%20Extensions%20SSL%20Library%20Linux%20Developer%20Guide.pdf) or that [for Windows](https://github.com/intel/intel-sgx-ssl/blob/master/Windows/package/docs/Intel(R)%20Software%20Guard%20Extensions%20SSL%20Library%20Windows%20Developer%20Guide.pdf). 
The reference will be corrected.

**Comment by jinghe-INTC** [comment]
The sentences will be changed from 
```
Unsupported OpenSSL APIs included in the Intel® SGX SSL cryptographic library are not validated or recommended. See Appendix A for the supported OpenSSL APIs.

In addition, the Intel® SGX SSL library exposes a closed set of manageability APIs, a list of which is provided in Supported APIs.
```
to
```
Unsupported OpenSSL APIs included in the Intel® SGX SSL cryptographic library are not validated or recommended. See Appendix A for the supported OpenSSL APIs in the developer guide.

In addition, the Intel® SGX SSL library exposes a closed set of manageability APIs, a list of which is provided in Supported APIs in the developer guide.
```

**Comment by jinghe-INTC** [comment]
I would like to close the case soon since the architecture doc has been corrected. Please let me know if you have  any other concern about it.
