### ISSUE TITLE
sgxssl_read implementation as OCALL

### ISSUE THREAD

**Issue by srieyulianti** [intel/intel-sgx-ssl#118]
Hi Intel team,

I want to implement TLS channel that should be termintaed inside enclave. I am using `intel-sgx-ssl` and `openssl`. I implement an example provided by [OpenSSL](https://wiki.openssl.org/index.php/Simple_TLS_Server) and it is running well outside the enclave. However, when I port the handling connection part into the enclave, I always got error related to `sgxssl_read`. Then I track that error and look to the `tunistd.cpp`, and I notice you mention something about this:
```
// In addition, the function is used by bss_sock.c as readsocket function.
// It is unreachable under the assumption that TLS support is not required.
// Otherwise should be implemented as OCALL.
```
I implement OCALL function to read the buffer from socket as below:
```
#include <sys/types.h>
#include <sys/socket.h>
#include <openssl/bio.h>
#include <openssl/ssl.h>
#include <internal/sockets.h>
#include <string>
#include <unistd.h>

extern "C"{
    size_t ocall_recv(int sockfd, void *buf, size_t len)
    {
        return readsocket(sockfd,buf,len);
    }
}
```
And this is how `sgx_tsgxssl.edl` looks like:
```
enclave {
    
    from "sgx_tstdc.edl" import *;
    
    untrusted {
    	 void u_sgxssl_ftime([out, size=timeb_len] void * timeptr, uint32_t timeb_len);
         size_t ocall_recv(int sockfd, [in, size=len] void *buf, size_t len);
    };
};
```
And this is the new `sgxssl_read` function:
```
size_t sgxssl_read(int fd, void *buf, size_t count)
{
	FSTART;

	if (fd == FAKE_PIPE_READ_FD) {
		// With pipes the function is used only by the engines/e_dasync.c (dummy async engine).
		SGX_UNSUPPORTED_FUNCTION(SET_ERRNO);

		FEND;
		// On error, -1 is returned, and errno is set appropriately
		return -1;
	}
	size_t retValue;
	size_t retError = ocall_recv(&retValue, fd, buf, count);
	if(retError > 0)
	{
		ocall_print_string_lib("SGXSSL_READ: Bytes received is more than 0 bytes\n\n");
	}
	else if(retError == 0)
	{
		ocall_print_string_lib("SGXSSL_READ: Connection closed!\n\n");
	}
	else
	{
		ocall_print_string_lib("SGXSSL_READ: Recv failed!\n\n");
	}
	// In addition, the function is used by bss_sock.c as readsocket function.
	// It is unreachable under the assumption that TLS support is not required.
	// Otherwise should be implemented as OCALL.
	// SGX_UNREACHABLE_CODE(SET_NO_ERRNO);
	FEND;
	return 0;
}
```
However the ocall return value is always 0. I also try to give count size with certain number, but the return value is still the same. Do you know what is the issue? Is there anything I miss from the code implementation? Any support from you will be very valuable for me. 

Thanks and regards,
Sri

**Comment by jinghe-INTC** [comment]
Recently we added a new development branch [support_tls](https://github.com/intel/intel-sgx-ssl/tree/support_tls). Please check if it satisfies your requirement, or submit issues or PRs to it if necessary. 

Thanks

**Comment by srieyulianti** [comment]
Hi @jinghe-INTC ,

Thanks for your reply. Yes, it works so far. I will close this issue.

Regards,
Sri
