### ISSUE TITLE
No easy way to build the test app by hand

### ISSUE THREAD

**Issue by mechalas** [intel/intel-sgx-ssl#12]
The build procedure for the package builds the test app but then runs "make clean" immediately after the tests are done, even if you supply 'no-clean' as an argument to the build script. And because the Makefiles depend on shell variables, there is no easy way to do the build by hand.

**Comment by light1021** [comment]
Hi, I think it's easier to build the tests function with another project.  
1, untar the lib you build to your disk;
2, set link-path and include-path in your makefile;
3, copy the tests in the test_app to your project;
4, modify your make file to build the tests.

**Comment by light1021** [comment]
If possible, I can make a test_app project without dependencies on any other shell variables.

**Comment by mechalas** [comment]
One of the points of supplying a test application with the build is to give the developer a known-good application that they can go build and run in order to test their tool chain. If I can't get my own project to work, then step #1 is to try the test application and see if _it_ works.

**Comment by akryeem-INTC** [comment]
Test app can be built with simple `make` command now.
