### ISSUE TITLE
compilation errors

### ISSUE THREAD

**Issue by markvai** [intel/intel-sgx-ssl#13]
Hi, I am using the sgx ssl over linux and followed your instructions.

I am getting the following errors during compilation:

/home/mark/Downloads/sgxopenssl/intel-sgx-ssl/Linux/package/lib64/release/libsgx_tsgxssl.a(tsocket.o): In function `sgxssl_gai_strerror':
tsocket.cpp:(.text+0x4e1): undefined reference to `strerror'
/home/mark/Downloads/sgxopenssl/intel-sgx-ssl/Linux/package/lib64/release/libsgx_tsgxssl.a(tpthread.o): In function `sgxssl_pthread_rwlock_rdlock':
sgx_t.mk:128: recipe for target 'TEST.so' failed
tpthread.cpp:(.text+0xac): undefined reference to `sgx_thread_self'
tpthread.cpp:(.text+0xd5): undefined reference to `sgx_thread_mutex_lock'
make[1]: Leaving directory '/home/mark/sgx_work/project/SgxEnclaveMigration/HashTable/sgx/enclave_TEST'
tpthread.cpp:(.text+0xe7): undefined reference to `sgx_thread_cond_wait'
sgx/Makefile:2: recipe for target 'all' failed
tpthread.cpp:(.text+0xf9): undefined reference to `sgx_thread_mutex_unlock'
/home/mark/Downloads/sgxopenssl/intel-sgx-ssl/Linux/package/lib64/release/libsgx_tsgxssl.a(tpthread.o): In function `sgxssl_pthread_rwlock_wrlock':
tpthread.cpp:(.text+0x1f0): undefined reference to `sgx_thread_self'
tpthread.cpp:(.text+0x219): undefined reference to `sgx_thread_mutex_lock'
tpthread.cpp:(.text+0x237): undefined reference to `sgx_thread_cond_wait'
tpthread.cpp:(.text+0x257): undefined reference to `sgx_thread_cond_wait'
tpthread.cpp:(.text+0x263): undefined reference to `sgx_thread_self'
tpthread.cpp:(.text+0x26f): undefined reference to `sgx_thread_mutex_unlock'
/home/mark/Downloads/sgxopenssl/intel-sgx-ssl/Linux/package/lib64/release/libsgx_tsgxssl.a(tpthread.o): In function `sgxssl_pthread_rwlock_unlock':
tpthread.cpp:(.text+0x36b): undefined reference to `sgx_thread_mutex_lock'
tpthread.cpp:(.text+0x389): undefined reference to `sgx_thread_mutex_unlock'
tpthread.cpp:(.text+0x3c5): undefined reference to `sgx_thread_self'
tpthread.cpp:(.text+0x3e6): undefined reference to `sgx_thread_cond_broadcast'
tpthread.cpp:(.text+0x3f0): undefined reference to `sgx_thread_mutex_unlock'
/home/mark/Downloads/sgxopenssl/intel-sgx-ssl/Linux/package/lib64/release/libsgx_tsgxssl.a(tpthread.o): In function `sgxssl_pthread_getspecific':
tpthread.cpp:(.text+0x57e): undefined reference to `sgx_thread_self'
/home/mark/Downloads/sgxopenssl/intel-sgx-ssl/Linux/package/lib64/release/libsgx_tsgxssl.a(tpthread.o): In function `sgxssl_pthread_rwlock_destroy':
tpthread.cpp:(.text+0x6c8): undefined reference to `sgx_thread_cond_destroy'
tpthread.cpp:(.text+0x6d1): undefined reference to `sgx_thread_mutex_destroy'
/home/mark/Downloads/sgxopenssl/intel-sgx-ssl/Linux/package/lib64/release/libsgx_tsgxssl.a(tpthread.o): In function `sgxssl_pthread_setspecific':
tpthread.cpp:(.text+0xcca): undefined reference to `sgx_thread_self'
/home/mark/Downloads/sgxopenssl/intel-sgx-ssl/Linux/package/lib64/release/libsgx_tsgxssl.a(tpthread.o): In function `sgxssl_pthread_self':
tpthread.cpp:(.text+0x5e1): undefined reference to `sgx_thread_self'
/home/mark/Downloads/sgxopenssl/intel-sgx-ssl/Linux/package/lib64/release/libsgx_tsgxssl.a(tpthread.o): In function `stlpmtx_std::priv::_Rb_tree<void*, stlpmtx_std::less<void*>, stlpmtx_std::pair<void* const, RwlockInfo*>, stlpmtx_std::priv::_Select1st<stlpmtx_std::pair<void* const, RwlockInfo*> >, stlpmtx_std::priv::_MapTraitsT<stlpmtx_std::pair<void* const, RwlockInfo*> >, stlpmtx_std::allocator<stlpmtx_std::pair<void* const, RwlockInfo*> > >::_M_insert(stlpmtx_std::priv::_Rb_tree_node_base*, stlpmtx_std::pair<void* const, RwlockInfo*> const&, stlpmtx_std::priv::_Rb_tree_node_base*, stlpmtx_std::priv::_Rb_tree_node_base*)':
tpthread.cpp:(.text._ZN11stlpmtx_std4priv8_Rb_treeIPvNS_4lessIS2_EENS_4pairIKS2_P10RwlockInfoEENS0_10_Select1stIS9_EENS0_11_MapTraitsTIS9_EENS_9allocatorIS9_EEE9_M_insertEPNS0_18_Rb_tree_node_baseERKS9_SI_SI_[_ZN11stlpmtx_std4priv8_Rb_treeIPvNS_4lessIS2_EENS_4pairIKS2_P10RwlockInfoEENS0_10_Select1stIS9_EENS0_11_MapTraitsTIS9_EENS_9allocatorIS9_EEE9_M_insertEPNS0_18_Rb_tree_node_baseERKS9_SI_SI_]+0x39): undefined reference to `operator new(unsigned long, void*)'
tpthread.cpp:(.text._ZN11stlpmtx_std4priv8_Rb_treeIPvNS_4lessIS2_EENS_4pairIKS2_P10RwlockInfoEENS0_10_Select1stIS9_EENS0_11_MapTraitsTIS9_EENS_9allocatorIS9_EEE9_M_insertEPNS0_18_Rb_tree_node_baseERKS9_SI_SI_[_ZN11stlpmtx_std4priv8_Rb_treeIPvNS_4lessIS2_EENS_4pairIKS2_P10RwlockInfoEENS0_10_Select1stIS9_EENS0_11_MapTraitsTIS9_EENS_9allocatorIS9_EEE9_M_insertEPNS0_18_Rb_tree_node_baseERKS9_SI_SI_]+0xb8): undefined reference to `operator new(unsigned long, void*)'
tpthread.cpp:(.text._ZN11stlpmtx_std4priv8_Rb_treeIPvNS_4lessIS2_EENS_4pairIKS2_P10RwlockInfoEENS0_10_Select1stIS9_EENS0_11_MapTraitsTIS9_EENS_9allocatorIS9_EEE9_M_insertEPNS0_18_Rb_tree_node_baseERKS9_SI_SI_[_ZN11stlpmtx_std4priv8_Rb_treeIPvNS_4lessIS2_EENS_4pairIKS2_P10RwlockInfoEENS0_10_Select1stIS9_EENS0_11_MapTraitsTIS9_EENS_9allocatorIS9_EEE9_M_insertEPNS0_18_Rb_tree_node_baseERKS9_SI_SI_]+0x11f): undefined reference to `operator new(unsigned long, void*)'
/home/mark/Downloads/sgxopenssl/intel-sgx-ssl/Linux/package/lib64/release/libsgx_tsgxssl.a(tpthread.o): In function `stlpmtx_std::priv::_Rb_tree<unsigned int, stlpmtx_std::less<unsigned int>, stlpmtx_std::pair<unsigned int const, void (*)(void*)>, stlpmtx_std::priv::_Select1st<stlpmtx_std::pair<unsigned int const, void (*)(void*)> >, stlpmtx_std::priv::_MapTraitsT<stlpmtx_std::pair<unsigned int const, void (*)(void*)> >, stlpmtx_std::allocator<stlpmtx_std::pair<unsigned int const, void (*)(void*)> > >::_M_insert(stlpmtx_std::priv::_Rb_tree_node_base*, stlpmtx_std::pair<unsigned int const, void (*)(void*)> const&, stlpmtx_std::priv::_Rb_tree_node_base*, stlpmtx_std::priv::_Rb_tree_node_base*)':
tpthread.cpp:(.text._ZN11stlpmtx_std4priv8_Rb_treeIjNS_4lessIjEENS_4pairIKjPFvPvEEENS0_10_Select1stIS9_EENS0_11_MapTraitsTIS9_EENS_9allocatorIS9_EEE9_M_insertEPNS0_18_Rb_tree_node_baseERKS9_SI_SI_[_ZN11stlpmtx_std4priv8_Rb_treeIjNS_4lessIjEENS_4pairIKjPFvPvEEENS0_10_Select1stIS9_EENS0_11_MapTraitsTIS9_EENS_9allocatorIS9_EEE9_M_insertEPNS0_18_Rb_tree_node_baseERKS9_SI_SI_]+0x39): undefined reference to `operator new(unsigned long, void*)'
tpthread.cpp:(.text._ZN11stlpmtx_std4priv8_Rb_treeIjNS_4lessIjEENS_4pairIKjPFvPvEEENS0_10_Select1stIS9_EENS0_11_MapTraitsTIS9_EENS_9allocatorIS9_EEE9_M_insertEPNS0_18_Rb_tree_node_baseERKS9_SI_SI_[_ZN11stlpmtx_std4priv8_Rb_treeIjNS_4lessIjEENS_4pairIKjPFvPvEEENS0_10_Select1stIS9_EENS0_11_MapTraitsTIS9_EENS_9allocatorIS9_EEE9_M_insertEPNS0_18_Rb_tree_node_baseERKS9_SI_SI_]+0xb8): undefined reference to `operator new(unsigned long, void*)'
/home/mark/Downloads/sgxopenssl/intel-sgx-ssl/Linux/package/lib64/release/libsgx_tsgxssl.a(tpthread.o):tpthread.cpp:(.text._ZN11stlpmtx_std4priv8_Rb_treeIjNS_4lessIjEENS_4pairIKjPFvPvEEENS0_10_Select1stIS9_EENS0_11_MapTraitsTIS9_EENS_9allocatorIS9_EEE9_M_insertEPNS0_18_Rb_tree_node_baseERKS9_SI_SI_[_ZN11stlpmtx_std4priv8_Rb_treeIjNS_4lessIjEENS_4pairIKjPFvPvEEENS0_10_Select1stIS9_EENS0_11_MapTraitsTIS9_EENS_9allocatorIS9_EEE9_M_insertEPNS0_18_Rb_tree_node_baseERKS9_SI_SI_]+0x11f): more undefined references to `operator new(unsigned long, void*)' follow
/home/mark/Downloads/sgxopenssl/intel-sgx-ssl/Linux/package/lib64/release/libsgx_tsgxssl.a(tstring.o): In function `sgxssl___builtin___strcat_chk':
tstring.cpp:(.text+0x83): undefined reference to `strncat'
/home/mark/Downloads/sgxopenssl/intel-sgx-ssl/Linux/package/lib64/release/libsgx_tsgxssl.a(tcpu_utils.o): In function `sgxssl_cpuid_leaf_info':
tcpu_utils.cpp:(.text+0x101): undefined reference to `sgx_cpuid'
/home/mark/Downloads/sgxopenssl/intel-sgx-ssl/Linux/package/lib64/release/libsgx_tsgxssl.a(tmem_mgmt.o): In function `stlpmtx_std::priv::_Rb_tree<void*, stlpmtx_std::less<void*>, stlpmtx_std::pair<void* const, MmapInfo*>, stlpmtx_std::priv::_Select1st<stlpmtx_std::pair<void* const, MmapInfo*> >, stlpmtx_std::priv::_MapTraitsT<stlpmtx_std::pair<void* const, MmapInfo*> >, stlpmtx_std::allocator<stlpmtx_std::pair<void* const, MmapInfo*> > >::_M_insert(stlpmtx_std::priv::_Rb_tree_node_base*, stlpmtx_std::pair<void* const, MmapInfo*> const&, stlpmtx_std::priv::_Rb_tree_node_base*, stlpmtx_std::priv::_Rb_tree_node_base*)':
tmem_mgmt.cpp:(.text._ZN11stlpmtx_std4priv8_Rb_treeIPvNS_4lessIS2_EENS_4pairIKS2_P8MmapInfoEENS0_10_Select1stIS9_EENS0_11_MapTraitsTIS9_EENS_9allocatorIS9_EEE9_M_insertEPNS0_18_Rb_tree_node_baseERKS9_SI_SI_[_ZN11stlpmtx_std4priv8_Rb_treeIPvNS_4lessIS2_EENS_4pairIKS2_P8MmapInfoEENS0_10_Select1stIS9_EENS0_11_MapTraitsTIS9_EENS_9allocatorIS9_EEE9_M_insertEPNS0_18_Rb_tree_node_baseERKS9_SI_SI_]+0x39): undefined reference to `operator new(unsigned long, void*)'
tmem_mgmt.cpp:(.text._ZN11stlpmtx_std4priv8_Rb_treeIPvNS_4lessIS2_EENS_4pairIKS2_P8MmapInfoEENS0_10_Select1stIS9_EENS0_11_MapTraitsTIS9_EENS_9allocatorIS9_EEE9_M_insertEPNS0_18_Rb_tree_node_baseERKS9_SI_SI_[_ZN11stlpmtx_std4priv8_Rb_treeIPvNS_4lessIS2_EENS_4pairIKS2_P8MmapInfoEENS0_10_Select1stIS9_EENS0_11_MapTraitsTIS9_EENS_9allocatorIS9_EEE9_M_insertEPNS0_18_Rb_tree_node_baseERKS9_SI_SI_]+0xb8): undefined reference to `operator new(unsigned long, void*)'
tmem_mgmt.cpp:(.text._ZN11stlpmtx_std4priv8_Rb_treeIPvNS_4lessIS2_EENS_4pairIKS2_P8MmapInfoEENS0_10_Select1stIS9_EENS0_11_MapTraitsTIS9_EENS_9allocatorIS9_EEE9_M_insertEPNS0_18_Rb_tree_node_baseERKS9_SI_SI_[_ZN11stlpmtx_std4priv8_Rb_treeIPvNS_4lessIS2_EENS_4pairIKS2_P8MmapInfoEENS0_10_Select1stIS9_EENS0_11_MapTraitsTIS9_EENS_9allocatorIS9_EEE9_M_insertEPNS0_18_Rb_tree_node_baseERKS9_SI_SI_]+0x11f): undefined reference to `operator new(unsigned long, void*)'
/home/mark/Downloads/sgxopenssl/intel-sgx-ssl/Linux/package/lib64/release/libsgx_tsgxssl.a(texceptions.o): In function `init_exception_handler':
texceptions.c:(.text.startup+0x33): undefined reference to `sgx_cpuid'
texceptions.c:(.text.startup+0xa3): undefined reference to `sgx_cpuid'
/home/mark/Downloads/sgxopenssl/intel-sgx-ssl/Linux/package/lib64/release/libsgx_tsgxssl.a(bionic_sscanf.o): In function `sgxssl_vsscanf':
bionic_sscanf.c:(.text+0x79): undefined reference to `isspace'
bionic_sscanf.c:(.text+0xa1): undefined reference to `isspace'
bionic_sscanf.c:(.text+0x14b): undefined reference to `isupper'
bionic_sscanf.c:(.text+0x1a4): undefined reference to `isspace'
bionic_sscanf.c:(.text+0x629): undefined reference to `isspace'
bionic_sscanf.c:(.text+0x75f): undefined reference to `strtoumax'
bionic_sscanf.c:(.text+0x9e0): undefined reference to `isspace'
bionic_sscanf.c:(.text+0xa0c): undefined reference to `strtod'
bionic_sscanf.c:(.text+0xa88): undefined reference to `strtoimax'

**Comment by akryeem-INTC** [comment]
Hi,
What libraries your enclave link to? (apart from SGXSSL libraries).
Maybe you're missing linking SGX SDK libraries (libsgx_tstdc, libsgx_tstdcxx, libsgx_trts)? You may take a look at test_enclave Makefile and see what libraries it links to.

**Comment by akryeem-INTC** [comment]
Closing this issue.
Reopen if it still relevant.
