### ISSUE TITLE
tls from enclave to website

### ISSUE THREAD

**Issue by njeans** [intel/intel-sgx-ssl#146]
Hi, I am trying to create a tls connection to an external website (i.e. not another enclave) using the support-tls branch.. Is this supported? I can't tell from the readme and it has not been working for me. The enclave just stops if I try to call `SSL_connect` with no errors. 

If it is not supported is there any alternative library to do this?

**Comment by johnvenn** [comment]
The branch is a debug branch for one sample in Intel SGX SDK. SSL_connect should work but it was not fully tested.
