### ISSUE TITLE
Upgrade timeline for OpenSSL 1.1.1t?

### ISSUE THREAD

**Issue by CookieComputing** [intel/intel-sgx-ssl#151]
A recent advisory suggests that there are several vulnerabilities in 1.1.1s: https://www.openssl.org/news/secadv/20230207.txt. Is SGXSSL vulnerable to any of these concerns? Is there a timeline we can follow to understand when there will be an update?

**Comment by jinghe-INTC** [comment]
There was already one [PR](https://github.com/intel/intel-sgx-ssl/pull/150) for it.

**Comment by jinghe-INTC** [comment]
Upgrading was just done. Thanks.
