### ISSUE TITLE
When will the "support_tls" branch be merged into the "main" branch?

### ISSUE THREAD

**Issue by sword03** [intel/intel-sgx-ssl#156]
As shown in the title. The "tls" feature is a much needed feature. Wait too long for it.

**Comment by johnvenn** [comment]
hi, actually the support_tls branch is always synced with the main branch. You can check out support_tls branch for use, it supports both basic crypto functionalities and tls functionalities.

**Comment by johnvenn** [comment]
> Thanks for your answer. I wonder whether the "support_tls branch" has been tested enough?

yes, this is a trial branch and it is for SGX SDK SampleAttestedTLS.
Thanks a lot for your feedback, and adding more cases to test the TLS functions is actual in plan.

**Comment by sword03** [comment]
Hi， is the "tls" feature supported in Main branch now？

**Comment by johnvenn** [comment]
> Hi， is the "tls" feature supported in Main branch now？

not yet, we have some security concerns for IO operations in ocall. But we have upgraded suppport_tls to openssl3.0.0 in branch "support_tls_openssl3" which is also compatible with opnessl1.1

**Comment by sword03** [comment]
Is there a plan to support tls in branch "main"?

**Comment by sword03** [comment]
> > Hi， is the "tls" feature supported in Main branch now？
> 
> not yet, we have some security concerns for IO operations in ocall. But we have upgraded suppport_tls to openssl3.0.0 in branch "support_tls_openssl3" which is also compatible with openssl1.1


Is there a plan to support tls in branch "main"?

**Comment by johnvenn** [comment]
> > > Hi， is the "tls" feature supported in Main branch now？
> > 
> > 
> > not yet, we have some security concerns for IO operations in ocall. But we have upgraded suppport_tls to openssl3.0.0 in branch "support_tls_openssl3" which is also compatible with openssl1.1
> 
> Is there a plan to support tls in branch "main"?

we are discussing a proposal.
