### ISSUE TITLE
Linux - build_sgxssl.sh with latest sdk

### ISSUE THREAD

**Issue by dpreilan** [intel/intel-sgx-ssl#16]
I am using sgx_linux_x64_sdk_2.1.101.42529.bin and latest from this project.

The logic in build_sgxssl.sh around setting SGXSDK_VERSION is causing a later error attempting to build openssl. 

if [[ $# -gt 0 ]] && [[ $1 == "linux-sgx" || $2 == "linux-sgx" ]] ; then
    LINUX_BUILD_FLAG=LINUX_SGX_BUILD=1
    SGXSDK_VERSION=`/bin/grep -m 1 "STRFILEVER" ../../common/inc/internal/se_version.h | /bin/grep -o -E "[1-9]\.[0-9]"`
    SGX_SDK_LIBS_PATH=../../build/linux
else
    LINUX_BUILD_FLAG=LINUX_SGX_BUILD=0
    SGX_SDK=/opt/intel/sgxsdk
    SGXSDK_VERSION=`/bin/grep -m 1 "Version:" $SGX_SDK/pkgconfig/libsgx_urts.pc | /bin/grep -o -E "[1-9]\.[0-9]"`
    if [ -f $SGX_SDK/environment ]; then
        source $SGX_SDK/environment || clean_and_ret 1
    else
        echo "In order to run this script, Intel® Software Guard Extensions SDK 1.7 must be installed on this machine, and SGX_SDK (in this script) must be set to the installation location"
        clean_and_ret 1
    fi
fi

==============================================================
Test:

/bin/grep -m 1 "Version:" $SGX_SDK/pkgconfig/libsgx_urts.pc | /bin/grep -o -E "[1-9]\.[0-9]"
2.1
1.4

**Comment by akryeem-INTC** [comment]
Issue fixed.
