### ISSUE TITLE
Possibly need a bigger HeapMaxSize in enclave signing configuration since SGXSSL 3.0

### ISSUE THREAD

**Issue by jinghe-INTC** [intel/intel-sgx-ssl#171]
After upgrading to OpenSSL 3.0, it possibly needs to increase the number in the enclave signing configuration XML file:
`<HeapMaxSize>...</HeapMaxSize>`
, especially for the enclave with multithreads.

**Comment by ShundaZhang** [comment]
Do you have a recommended minimum value, for example, not less than 512KB?

**Comment by jinghe-INTC** [comment]
> Do you have a recommended minimum value, for example, not less than 512KB?

It is difficult to provide accurate numbers for different situations. User has to do fine tuning if need a minimum value.

**Comment by jinghe-INTC** [comment]
README.MD has been updated in commit [d664ac8](https://github.com/intel/intel-sgx-ssl/commit/d664ac8014be45f998bcb50261d3aac11bff0189) for it.
