### ISSUE TITLE
About developer license

### ISSUE THREAD

**Issue by imlibra** [intel/intel-sgx-ssl#19]
Is it possible to obtaining a licensed developer certificate for signing security-reviewed, community-developed open source SGX software binary in production mode, and publish it on open source repository like apt or rpm?

**Comment by akryeem-INTC** [comment]
@imlibra 
SGXSSL is only a plugin library that can be used by SGX developers.
You should forward your request to the SGX SDK GitHub repo.
https://github.com/intel/linux-sgx/
If you need any further assist, reopen.
