### ISSUE TITLE
undefined reference to 'strcmp' 

### ISSUE THREAD

**Issue by hjphabahaha** [intel/intel-sgx-ssl#212]
I am a beginner at SGX. How can I use SGX SSL? I have read Intel ®  Software Guard extensions SSL (Intel) ®  SGX SSL Library Linux Developer Guide. But I still have some confusion. I encountered 
/usr/local/bin/ld: tstdlib. cpp: (. text. sgxssl_getenv+0x44): undefined reference to ` strcmp '    
/Usr/local/bin/ld: tstdlib. cpp: (. text. sgxssl_getenv+0x57): undefined reference to 'strcmp'      error. 

I know it should be a makefile configuration error, but I don't know how to correct this error

**Comment by jinghe-INTC** [comment]
The error message `undefined reference to 'strcmp'` indicates that the enclave project is not linked to the `libsgx_tstdc` static library. To resolve this error, please refer to the [unit test project](https://github.com/intel/intel-sgx-ssl/tree/main/Linux/sgx/test_app).

**Comment by jinghe-INTC** [comment]
@hjphabahaha I'm closing this issue. If you're still experiencing this problem, please look at the unit test project to correct the error.
