### ISSUE TITLE
Fail to use EVP_* functions within enclave

### ISSUE THREAD

**Issue by tyler-lee** [intel/intel-sgx-ssl#22]
Hi all, I try to call openssl EVP_* functions within enclave. It turns out a lot of "undefined reference to '.....'". Has any body make this out? Or does intel-sgx-ssl support such a scheme?

**Comment by akryeem-INTC** [comment]
SGXSSL does support calling EVP_* APIs.

Can you provide some additional info? maybe you're missing some library linkage? what errors are you getting? how your Makefile looks like?

**Comment by naishai** [comment]
try to place the sgx-ssl libraries before the regular sgx libraries in the linker line
also note the the tsgxssl library should be wrapped with 'whole-archive' flag (-Wl,--whole-archive -lsgx_tsgxssl -Wl,--no-whole-archive)

**Comment by tyler-lee** [comment]
It works now! Thanks for your help.

**Comment by tyler-lee** [comment]
One more question: EVP_aes_* in OpenSSL enable AESNI by default. Does EVP_aes_* in sgx ssl enable it by default too?

**Comment by akryeem-INTC** [comment]
Yeah

**Comment by faysalhossain2007** [comment]
I am facing the same problem. Can you please tell me in details what should I do in Linker file?

**Comment by chanheehan0630** [comment]
hello~~ can i ask u something??

I've run it in a linux environment and help me get something like this.

sed: can't read openssl_1.1.1.orig/Configure: No such file or directory
sed: can't read openssl_1.1.1.orig/crypto/uid.c: No such file or directory
Makefile:55: recipe for target '/home/sgx/intel-sgx-ssl/intel-sgx-ssl/Linux/sgx/../package/lib64//libsgx_tsgxssl_crypto.a' failed
make[1]: *** [/home/sgx/intel-sgx-ssl/intel-sgx-ssl/Linux/sgx/../package/lib64//libsgx_tsgxssl_crypto.a] Error 1
make[1]: Leaving directory '/home/sgx/intel-sgx-ssl/intel-sgx-ssl/Linux/sgx'
Makefile:39: recipe for target 'all' failed
make: *** [all] Error 2

what should i do?

**Comment by akryeem-INTC** [comment]
Can you please make sure that openssl_source/ directory is clean, and it doesn't include any corrupted openssl packages?

**Comment by chanheehan0630** [comment]
openssl_directory has like these. "bypass_to_sgxssl.h  openssl-1.1.1  openssl_1.1.1.orig.tar.gz  rand_lib.c  sgx_config.conf" and how to check about corrupted openssl packages?

**Comment by akryeem-INTC** [comment]
``openssl_1.1.1.orig.tar.gz`` name should be ``openssl_1.1.1.tar.gz``
