### ISSUE TITLE
Build Configuration

### ISSUE THREAD

**Issue by faysalhossain2007** [intel/intel-sgx-ssl#26]
I am getting build error. Can you tell me how I am going to change the required file location in the build file? I mean where to put the openssl source directory and perl, NASM, 7zip install location?

**Comment by akryeem-INTC** [comment]
What kind of build errors are you getting? Could you paste it here?
You need to install perl, NASM, 7zip and add it to your environment path. OpenSSL tar.gz package should be in openssl_source/ directory.

**Comment by faysalhossain2007** [comment]
I have already installed those software. And added into the environment path. And put the OpenSSL file(after extracting) that I have downloaded from the openssl website. Do I need to change any configuration file to tell the code my installed software directory and openssl directory?

**Comment by akryeem-INTC** [comment]
> (after extracting)
This is not needed, just put tar.gz file in openssl_source/ dir.
You don't need to do any other changes. Can't you tell what build errors are you getting? I need it inorder to understand what is the issue and how to help with it.

**Comment by faysalhossain2007** [comment]
I put openssl-1.0.2j-fips-x86_64.zip inside "intel-sgx-ssl-master\openssl_source" folder. And then executed build_all.cmd by clicking it. Still getting errors. I am attaching the errors here. 
![intel-sgx-error-1](https://user-images.githubusercontent.com/1239654/42601153-a6b8e636-8532-11e8-9bfb-46c5307bf9cc.PNG)
![intel-sgx-file-2](https://user-images.githubusercontent.com/1239654/42601154-a6c53742-8532-11e8-910f-f27f6f93fbe1.PNG)
![intel-sgx-file-3](https://user-images.githubusercontent.com/1239654/42601155-a6d0cb70-8532-11e8-8572-99ef7b24ecf4.PNG)

**Comment by akryeem-INTC** [comment]
Please look at README carefully and try again.
This SGXSSL version is intended to work with OpenSSL 1.1.0 version and not 1.0.2.

**Comment by faysalhossain2007** [comment]
I have downloaded OpenSSL 1.10g  from https://ftp.openssl.org/source/old/1.1.0/ . But Still I am getting the same error. 
After some investigation I have found that whenever I ran the build_all.cmd it automatically deletes openssl-1.1.0g from the open_ssl source directory. And after that It triggers that it cannot find the open ssl file.

**Comment by faysalhossain2007** [comment]
I am now getting the following error: 
![intel-sgx-error](https://user-images.githubusercontent.com/1239654/42659778-4df03700-85f7-11e8-9437-d1694f302080.PNG)

**Comment by faysalhossain2007** [comment]
I am getting the following errors. What should I do now? 


![sgx-error-1](https://user-images.githubusercontent.com/1239654/42662932-7a60d1c8-8601-11e8-98cf-884cdd19dcd2.PNG)
![sgx-error-2](https://user-images.githubusercontent.com/1239654/42662933-7a6ba486-8601-11e8-8640-42ce5b135a31.PNG)

**Comment by faysalhossain2007** [comment]
Do you have any suggestion for this error?

**Comment by akryeem-INTC** [comment]
Is this still relevant?
Could you mention what you've done step-by-step? it's hard to understand what's going on by looking on some screenshots, give normal text feedback and not screenshots.
