### ISSUE TITLE
Rand_seed && Rand_add

### ISSUE THREAD

**Issue by light1021** [intel/intel-sgx-ssl#27]
Hi all:
I read the document it said that sgxssl support Rand_seed and Rand_add, but I cant find these functions in any header files. So how can I use these functions. Thanks !
Regards you

**Comment by light1021** [comment]
In my case I want to generate Rsa key inside Enclave with a hardware random generator. So how can I reset the sgxssl random sourse to my own. Thanks !!!
Regards you

**Comment by naishai** [comment]
You can define your own RAND_METHOD structure, and then call RAND_set_rand_method to set it as the active random engine.
This is more an OpenSSL question, not really SGXSSL one.
BTW - SGXSSL replaces the OpenSSL random source, and use sgx_read_rand as the source of randomness, which in turn uses rdrand opcode, which is also hardware based random generator.
You can check out the following files for more info:
intel-sgx-ssl/Linux/sgx/libsgx_tsgxssl/trand.cpp
and the ones in intel-sgx-ssl/openssl_source/

**Comment by light1021** [comment]
Hi naishai:
 Thank you for your replay. It's helpful :wink:. I konw this is mostly an openssl question, but I have no idea which methods are supported inside Enclave. I will try your advice. 
Regards you

**Comment by light1021** [comment]
Solved, Now this case can be closed. Thank you very much.
