### ISSUE TITLE
openssl 1.1.1 support

### ISSUE THREAD

**Issue by light1021** [intel/intel-sgx-ssl#28]
Hi all:
Is there any plan to support openssl1.1.1? If not, Can I make it work some way. I can successfully compile and get the static lib files. But when I use that in my project, there are some link errors:
[ 76%] Linking CXX shared library libEnclave.so
CMakeFiles/Enclave.dir/Enclave.cpp.o：在函数‘ecall_say_hello’中：
/home/ywl/Documents/sgx-template/Enclave/Enclave.cpp:163：对‘SGXSSLGetSgxSSLVersion’未定义的引用
/opt/intel/sgxssl/lib64/debug/libsgx_tsgxssl_crypto.a(init.o)：在函数‘OPENSSL_fork_child’中：
init.c:(.text+0xa81)：对‘rand_fork’未定义的引用
/opt/intel/sgxssl/lib64/debug/libsgx_tsgxssl_crypto.a(mem_sec.o)：在函数‘CRYPTO_secure_malloc_init’中：
mem_sec.c:(.text+0xd71)：对‘syscall’未定义的引用
/opt/intel/sgxssl/lib64/debug/libsgx_tsgxssl_crypto.a(drbg_lib.o)：在函数‘RAND_DRBG_instantiate’中：
drbg_lib.c:(.text+0x29f)：对‘rand_pool_free’未定义的引用
/opt/intel/sgxssl/lib64/debug/libsgx_tsgxssl_crypto.a(drbg_lib.o)：在函数‘rand_drbg_restart’中：
drbg_lib.c:(.text+0x853)：对‘rand_pool_free’未定义的引用
drbg_lib.c:(.text+0x8d6)：对‘rand_pool_free’未定义的引用
drbg_lib.c:(.text+0x915)：对‘rand_pool_new’未定义的引用
drbg_lib.c:(.text+0x931)：对‘rand_pool_add’未定义的引用
/opt/intel/sgxssl/lib64/debug/libsgx_tsgxssl_crypto.a(drbg_lib.o)：在函数‘RAND_DRBG_generate’中：
drbg_lib.c:(.text+0xac4)：对‘rand_fork_count’未定义的引用
/opt/intel/sgxssl/lib64/debug/libsgx_tsgxssl_crypto.a(drbg_lib.o)：在函数‘RAND_DRBG_bytes’中：
drbg_lib.c:(.text+0xd78)：对‘rand_drbg_get_additional_data’未定义的引用
/opt/intel/sgxssl/lib64/debug/libsgx_tsgxssl_crypto.a(drbg_lib.o)：在函数‘RAND_DRBG_secure_new’中：
drbg_lib.c:(.text+0xf82)：对‘rand_fork_count’未定义的引用
drbg_lib.c:(.text+0xf8e)：对‘rand_drbg_get_entropy’未定义的引用
drbg_lib.c:(.text+0xf9c)：对‘rand_drbg_cleanup_entropy’未定义的引用
drbg_lib.c:(.text+0x107b)：对‘rand_drbg_get_nonce’未定义的引用
drbg_lib.c:(.text+0x1092)：对‘rand_drbg_cleanup_nonce’未定义的引用
/opt/intel/sgxssl/lib64/debug/libsgx_tsgxssl_crypto.a(drbg_lib.o)：在函数‘RAND_DRBG_new’中：
drbg_lib.c:(.text+0x114f)：对‘rand_fork_count’未定义的引用
drbg_lib.c:(.text+0x1162)：对‘rand_drbg_get_entropy’未定义的引用
drbg_lib.c:(.text+0x1170)：对‘rand_drbg_cleanup_entropy’未定义的引用
drbg_lib.c:(.text+0x1253)：对‘rand_drbg_get_nonce’未定义的引用
drbg_lib.c:(.text+0x126a)：对‘rand_drbg_cleanup_nonce’未定义的引用
/opt/intel/sgxssl/lib64/debug/libsgx_tsgxssl_crypto.a(threads_pthread.o)：在函数‘fork_once_func’中：
threads_pthread.c:(.text+0x16)：对‘pthread_atfork’未定义的引用
/opt/intel/sgxssl/lib64/debug/libsgx_tsgxssl_crypto.a(bn_rand.o)：在函数‘bnrand.part.0’中：
bn_rand.c:(.text+0xe9)：对‘RAND_priv_bytes’未定义的引用
/opt/intel/sgxssl/lib64/debug/libsgx_tsgxssl_crypto.a(bn_rand.o)：在函数‘BN_priv_rand’中：
bn_rand.c:(.text+0x750)：对‘RAND_priv_bytes’未定义的引用
/opt/intel/sgxssl/lib64/debug/libsgx_tsgxssl_crypto.a(bn_rand.o)：在函数‘BN_generate_dsa_nonce’中：
bn_rand.c:(.text+0xa99)：对‘RAND_priv_bytes’未定义的引用
/opt/intel/sgxssl/lib64/debug/libsgx_tsgxssl_crypto.a(ecx_meth.o)：在函数‘pkey_ecx_keygen’中：
ecx_meth.c:(.text+0x1648)：对‘RAND_priv_bytes’未定义的引用
ecx_meth.c:(.text+0x16d4)：对‘RAND_priv_bytes’未定义的引用
/opt/intel/sgxssl/lib64/debug/libsgx_tsgxssl_crypto.a(ecx_meth.o):ecx_meth.c:(.text+0x17d0): 跟着更多未定义的参考到 RAND_priv_bytes
/opt/intel/sgxssl/lib64/debug/libsgx_tsgxssl_crypto.a(loader_file.o)：在函数‘file_open’中：
loader_file.c:(.text+0xdd0)：对‘stat’未定义的引用
/opt/intel/sgxssl/lib64/debug/libsgx_tsgxssl_crypto.a(uid.o)：在函数‘OPENSSL_issetugid’中：
uid.c:(.text+0xa)：对‘getauxval’未定义的引用
/opt/intel/sgxssl/lib64/debug/libsgx_tsgxssl_crypto.a(o_dir.o)：在函数‘OPENSSL_DIR_read’中：
o_dir.c:(.text+0x42)：对‘readdir’未定义的引用
o_dir.c:(.text+0x9e)：对‘opendir’未定义的引用
/opt/intel/sgxssl/lib64/debug/libsgx_tsgxssl_crypto.a(o_dir.o)：在函数‘OPENSSL_DIR_end’中：
o_dir.c:(.text+0x11a)：对‘closedir’未定义的引用
/opt/intel/sgxssl/lib64/debug/libsgx_tsgxssl_crypto.a(conf_def.o)：在函数‘def_load_bio’中：
conf_def.c:(.text+0xf83)：对‘stat’未定义的引用
collect2: error: ld returned 1 exit status
Enclave/CMakeFiles/Enclave.dir/build.make:105: recipe for target 'Enclave/libEnclave.so' failed
make[2]: *** [Enclave/libEnclave.so] Error 1
CMakeFiles/Makefile2:262: recipe for target 'Enclave/CMakeFiles/Enclave.dir/all' failed
make[1]: *** [Enclave/CMakeFiles/Enclave.dir/all] Error 2`
`

**Comment by akryeem-INTC** [comment]
Hi,
OpenSSL 1.1.1 already supported in: [support_openssl_1_1_1 branch](https://github.com/intel/intel-sgx-ssl/tree/support_openssl_1_1_1) for Linux and Windows.
You can work with it.

**Comment by light1021** [comment]
Hi akryeem-INTC:
Thanks  very much !!!
