### ISSUE TITLE
Terminate TLS Connection Inside Enclave? 

### ISSUE THREAD

**Issue by vedantroy** [intel/intel-sgx-ssl#30]
Does intel-sgx-ssl support terminating a TLS connection inside an enclave directly/indirectly? If so, does any sample code exist that demonstrates how to do this?

**Comment by akryeem-INTC** [comment]
The current SGXSSL version only support and build OpenSSL crypto library. Hence, you can't call OpenSSL TLS APIs inside enclave.
If your question referred to a different operation, please explain.
