### ISSUE TITLE
Cannot debug enclave after linking sgx-ssl

### ISSUE THREAD

**Issue by jgharehchamani** [intel/intel-sgx-ssl#35]
Hi
I have used intel-sgx-ssl in my app. It works correctly when I run it. But when I want to debug my enclave and put breakpoint in a function, it gives me a segmentation fault. I tried to figure out the reason and I noticed that when I separate sgx-ssl lib from my code, debugging works again.
I have used DEBUG=1 option in the compilation and it does not fix the issue. Could you please help me?

**Comment by naishai** [comment]
on startup, openssl calls cpuid opcode 4 times to initialize internal variables. when this happens inside the enclave, each such call creates an exception - which is being caught and handled by the sgx-ssl code. in the debugger, you simply need to hit 'c' (continue) 4 times until you pass this initialization phase.

**Comment by jgharehchamani** [comment]
Thank you. It works now.
