### ISSUE TITLE
Is there a comprehensive evaluation about sgxssl's performance?

### ISSUE THREAD

**Issue by bronzeMe** [intel/intel-sgx-ssl#36]
Hi, is there a comprehensive evaluation about sgxssl's performance?
Or, a comparsion between original openssl and sgxssl?
Recently, I used the sgxssl to implement RSA-related compuation, but excuting RSA-related tasks inside enclave performances negative (-20%),
What is the root cause own to this?
is there any optimate method?

Thanks.

**Comment by akryeem-INTC** [comment]
Hi,
In issue #34 SgxSSL performance is discussed and compared to native OpenSSL performance with EC operations, you may take a look at it, you could also try using the benchmark mentioned there.

When running inside enclave the enclave special operations (e.g. entering and exiting the enclave) has an expected performance effect. But, this overhead is not expected to reach 20% degradation.
Could you provide some more info? RSA operations used, SgxSSL version, OpenSSL versions, SgxSDK version...

**Comment by akryeem-INTC** [comment]
Closing,
Reopen if it still relevant.
