### ISSUE TITLE
Undefined reference to TLS_method(), SSL_CTX_new(), and 10 more

### ISSUE THREAD

**Issue by gogo9th** [intel/intel-sgx-ssl#37]
Hi, 

When I compile  my SGX app, I get a lot of undefined reference errors: 

undefined reference to `TLS_method'
undefined reference to `SSL_CTX_new'
undefined reference to `SSL_CTX_callback_ctrl'
undefined reference to `SSL_CTX_set_default_passwd_cb'
undefined reference to `SSL_CTX_set_default_passwd_cb_userdata'
undefined reference to `SSL_CTX_use_certificate_file'
undefined reference to `SSL_CTX_use_PrivateKey_file'
undefined reference to `SSL_CTX_check_private_key'
undefined reference to `SSL_CTX_load_verify_locations'
undefined reference to `SSL_CTX_set_verify'
undefined reference to `SSL_CTX_set_options'

I don't find any of these function definitions in the following SGX libraries: 
libsgx_tsgxssl.a  libsgx_tsgxssl_crypto.a  libsgx_usgxssl.a

How can I properly use the above 12 functions from within my program?

**Comment by akryeem-INTC** [comment]
Currently the SgxSSL library only supports cryptographic OpenSSL APIs, see user's guide for more info. TLS/SSL APIs is not supported.
