### ISSUE TITLE
Potential memory leak in the TestEnclave.cpp?

### ISSUE THREAD

**Issue by ShaleXIONG** [intel/intel-sgx-ssl#39]
In the Linux/sgx/test_app/enclave/TestEnclave.cpp line 194 : i2d_PublicKey call followed by malloc then another i2d_PublicKey. The openssl document says `Using a temporary variable is mandatory`, ie no need for a malloc otherwise it might contain garbage.

**Comment by akryeem-INTC** [comment]
There is no memory leak here.
In `i2d_PublicKey` documentation you can see: `If *ppout is NULL memory will be allocated`, in the TestApp ppout itself is NULL, hence we're in the `otherwise it returns the length of the encoded data.` case.
