### ISSUE TITLE
Recommended to update the filter command

### ISSUE THREAD

**Issue by cstwhh** [intel/intel-sgx-ssl#43]
https://github.com/intel/intel-sgx-ssl/blob/19c638deaa0c05eeec90ab7a832aa321f0f4ed89/Linux/build_openssl.sh#L41
This script is only compatible with the openssl-1.1.1 version, so it is recommended to change it to `/bin/ls $SGXSSL_ROOT/../openssl_source/*1.1.1*.tar.gz | /usr/bin/head -1 | /bin/grep -o '[^/]*$' | /bin/sed -s -- 's/\.tar\.gz//'`
Problem scenario: I used openssl-1.1.0 before, after a while I tried to update to openssl-1.1.1. When running this script, it unfortunately first found the openssl-1.1.0 I downloaded before, then used the version of 1.1.0 incorrectly. Although the problem is simple, it has brought me some confusion.

**Comment by akryeem-INTC** [comment]
Done
