### ISSUE TITLE
make all test error

### ISSUE THREAD

**Issue by chanheehan0630** [intel/intel-sgx-ssl#44]
I ran 'make all test' and got this error

sgx@sgx-desktop:~/intel-sgx-ssl/intel-sgx-ssl/Linux$ make all test
make -C sgx/ all
make[1]: Entering directory '/home/sgx/intel-sgx-ssl/intel-sgx-ssl/Linux/sgx'
make -C /home/sgx/intel-sgx-ssl/intel-sgx-ssl/Linux/sgx/libsgx_tsgxssl/ all
make[2]: Entering directory '/home/sgx/intel-sgx-ssl/intel-sgx-ssl/Linux/sgx/libsgx_tsgxssl'
make[2]: *** No rule to make target '/bin/x64/sgx_edger8r', needed by 'sgx_tsgxssl_t.c'.  Stop.
make[2]: Leaving directory '/home/sgx/intel-sgx-ssl/intel-sgx-ssl/Linux/sgx/libsgx_tsgxssl'
Makefile:47: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/sgx/intel-sgx-ssl/intel-sgx-ssl/Linux/sgx'
Makefile:39: recipe for target 'all' failed
make: *** [all] Error 2

what's wrong?

**Comment by akryeem-INTC** [comment]
You need to source SGX SDK environment before running build.
