### ISSUE TITLE
Build failure with openssl-1.1.1c

### ISSUE THREAD

**Issue by gingerbeard-man** [intel/intel-sgx-ssl#45]
Building on RHEL 8 with openssl-1.1.1c.tar.gz fails, due to prototype mismatch for rand_pool_new() provided in the recently updated openssl_source/rand_lib.c vs. OpenSSL's original crypto/include/internal/rand_int.h.
With openssl-1.1.1d.tar.gz the build succeeds.  (It appears the function gained a 4th argument in 1.1.1d.)

Is there an implicit requirement to always use the latest OpenSSL release?  If yes, I suggest to add some information about this in the README, e.g. the minimum supported version.
If it is still supported to build with 1.1.1a, b or c then instructions on how to do so would be helpful.

**Comment by akryeem-INTC** [comment]
Master branch will always support latest OpenSSL version with latest SGX SDK.
In order to use an old version, you can checkout the tag relevant to your version, e.g. lin_2.5_1.1.1c.

**Comment by gingerbeard-man** [comment]
Thank you for this information.  A build with tag lin_2.5_1.1.1c and openssl-1.1.1c.tar.gz was successful.

I still think it would be useful to mention this in a sentence or two in the README.  There is a hint about OpenSSL 1.1.0 but nothing about how to work with earlier versions of 1.1.1.
