### ISSUE TITLE
Can't use sgxssl suit from within an sgxsdk example enclave

### ISSUE THREAD

**Issue by BoujdadFz** [intel/intel-sgx-ssl#46]
Hello, 
I'm trying to use the library from within an enclave in the SampleCode/SampleEnclave directory of the sgxsdk after installing sgxssl..
so I tried simply including <openssl/bn.h>  but it doesn't find the file; as a result, I added sgxssl include and library paths in the Makefile of the application enclave, but then I get the error reported below, I still have no clue how to use intel-sgx-ssl suit. Please help me with some hints if any and thank you in advance.

In file included from /usr/include/x86_64-linux-gnu/c++/6/bits/gthr.h:148:0,
                 from /usr/include/c++/6/ext/atomicity.h:35,
                 from /usr/include/c++/6/bits/basic_string.h:39,
                 from /usr/include/c++/6/string:52,
                 from /usr/include/c++/6/stdexcept:39,
                 from /usr/include/c++/6/array:39,
                 from /usr/include/c++/6/tuple:39,
                 from /usr/include/c++/6/functional:55,
                 from /usr/include/c++/6/thread:39,
                 from App/TrustedLibrary/Thread.cpp:33:
/usr/include/x86_64-linux-gnu/c++/6/bits/gthr-default.h:50:9: error: ‘pthread_mutex_t’ does not name a type
 typedef pthread_mutex_t __gthread_mutex_t;
         ^~~~~~~~~~~~~~~
/usr/include/x86_64-linux-gnu/c++/6/bits/gthr-default.h:51:9: error: ‘pthread_mutex_t’ does not name a type
 typedef pthread_mutex_t __gthread_recursive_mutex_t;
         ^~~~~~~~~~~~~~~
/usr/include/x86_64-linux-gnu/c++/6/bits/gthr-default.h:52:9: error: ‘pthread_cond_t’ does not name a type
 typedef pthread_cond_t __gthread_cond_t;
         ^~~~~~~~~~~~~~
/usr/include/x86_64-linux-gnu/c++/6/bits/gthr-default.h:101:1: error: ‘pthread_once’ was not declared in this scope
 __gthrw(pthread_once)
 ^
/usr/include/x86_64-linux-gnu/c++/6/bits/gthr-default.h:102:1: error: ‘pthread_getspecific’ was not declared in this scope
.
.
.

**Comment by naishai** [comment]
Hi,
Please read the main readme file, and in it you can find links to detailed user manual that describes exactly how to use SGXSSL.
If you still have issues after you've followed it, please provide more details.

**Comment by BoujdadFz** [comment]
Hi,
Thanks for your remark. I applied what's in the guide. I"m now getting this when making SampleCode/SampleEnclave:

error: Multiple definition of function "sgx_thread_wait_untrusted_event_ocall" detected.

I think this is because of the header file pthread.h;  in the guide for setting the ssl environment for the Enclave Project, step 4 says something about it : "The Intel SGX SSL include path also includes a reduced "pthread.h" file ...Make sure it is not in the path of your regular application as it may cause compilation errors."

But I honestly don't understand what it means. By regular application is it meant the Application Project?  I don't know what to do to satisfy step 4.  

Can you please help me as to this? thanks

**Comment by BoujdadFz** [comment]
Fine, I finally could build the SampleCode/SampleEnclave project, what I did is putting the line 'from sgx_tsgxssl.edl' import *' before the other import lines, then I got other linking errors which was resolved by placing the sgx ssl libraries before the sdk libraries for the Enclave project linker.
