### ISSUE TITLE
Build issues on master revision

### ISSUE THREAD

**Issue by Arslan8** [intel/intel-sgx-ssl#57]
Hi, 
I've been trying to build intel-sgx-ssl on Ubuntu 18.04. I've tried two configurations. 
1. With the flag -mlfence-before-ret=not and -mlfence-after-load=yes for as. In this configuration I used the same as that is shipped with the ubuntu 18.04. Since this is the older version of as it does not support this flag. To modify this i removed the flags from the build. However along the build i got the error:
`g++ enclave/TestEnclave_t.o enclave/TestEnclave.o enclave/tests/ecdhtest.o enclave/tests/sha1test.o enclave/tests/missing_funcs.o enclave/tests/threadstest.o enclave/tests/stdio_func.o enclave/tests/dhtest.o enclave/tests/ecdsatest.o enclave/tests/rsa_test.o enclave/tests/bntest.o enclave/tests/sha256t.o enclave/tests/ectest.o -o TestEnclave.so -m64 -Wall -O2 -D_FORTIFY_SOURCE=2 -Wl,--no-undefined -nostdlib -nodefaultlibs -nostartfiles -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -pie -L/home/arslan/Documents/sgxsdk/sgxsdk/SampleCode/ssl2/intel-sgx-ssl/Linux/sgx/../package/lib64// -Wl,--whole-archive -lsgx_tsgxssl -Wl,--no-whole-archive -lsgx_tsgxssl_crypto -L/home/arslan/Documents/sgxsdk/sgxsdk/lib64 -Wl,--whole-archive -lsgx_trts -Wl,--no-whole-archive -Wl,--start-group -lsgx_tstdc -lsgx_tcxx -lsgx_tcrypto  -lsgx_tservice -Wl,--end-group -Wl,-Bstatic -Wl,-Bsymbolic -Wl,--no-undefined -Wl,-pie,-eenclave_entry -Wl,--export-dynamic -Wl,--defsym,__ImageBase=0 -Wl,--version-script=enclave/TestEnclave.lds
/home/arslan/Documents/sgxsdk/sgxsdk/SampleCode/ssl2/intel-sgx-ssl/Linux/sgx/../package/lib64///libsgx_tsgxssl.a(tstdlib.o): In function `tssl_access_version_dummy1()':
tstdlib.cpp:(.text.exit._Z26tssl_access_version_dummy1v+0xb): undefined reference to `__x86_return_thunk'
/home/arslan/Documents/sgxsdk/sgxsdk/SampleCode/ssl2/intel-sgx-ssl/Linux/sgx/../package/lib64///libsgx_tsgxssl.a(tstdlib.o): In function `sgxssl_getenv':
tstdlib.cpp:(.text.sgxssl_getenv+0xb5): undefined reference to `__x86_return_thunk'
tstdlib.cpp:(.text.sgxssl_getenv+0xc8): undefined reference to `__x86_return_thunk'
/home/arslan/Documents/sgxsdk/sgxsdk/SampleCode/ssl2/intel-sgx-ssl/Linux/sgx/../package/lib64///libsgx_tsgxssl.a(tstdlib.o): In function `sgxssl_atexit':
tstdlib.cpp:(.text.sgxssl_atexit+0x3): undefined reference to `__x86_return_thunk'
/home/arslan/Documents/sgxsdk/sgxsdk/SampleCode/ssl2/intel-sgx-ssl/Linux/sgx/../package/lib64///libsgx_tsgxssl.a(tmem_mgmt.o): In function `std::__1::map<void*, MmapInfo*, std::__1::less<void*>, std::__1::allocator<std::__1::pair<void* const, MmapInfo*> > >::~map()':
tmem_mgmt.cpp:(.text._ZNSt3__13mapIPvP8MmapInfoNS_4lessIS1_EENS_9allocatorINS_4pairIKS1_S3_EEEEED2Ev[_ZNSt3__13mapIPvP8MmapInfoNS_4lessIS1_EENS_9allocatorINS_4pairIKS1_S3_EEEEED5Ev]+0xf): undefined reference to `__x86_return_thunk'
/home/arslan/Documents/sgxsdk/sgxsdk/SampleCode/ssl2/intel-sgx-ssl/Linux/sgx/../package/lib64///libsgx_tsgxssl.a(tmem_mgmt.o):tmem_mgmt.cpp:(.text.sgxssl_mprotect+0x6a): more undefined references to `__x86_return_thunk' follow`
2. The other configuration i tried was with the build flags. I built the latest binutils and it was able to recognize the flag. However, in this case, I also run into a somewhat similar but different error:
`/home/arslan/trunk/bin/ld: /home/arslan/Documents/sgxsdk/sgxsdk/SampleCode/intel-sgx-ssl/Linux/sgx/../package/lib64///libsgx_tsgxssl_crypto.a(hkdf.o): in function `pkey_hkdf_ctrl':
hkdf.c:(.text+0x77): undefined reference to `__x86_return_thunk'
/home/arslan/trunk/bin/ld: hkdf.c:(.text+0x97): undefined reference to `__x86_return_thunk'
/home/arslan/trunk/bin/ld: hkdf.c:(.text+0xbd): undefined reference to `__x86_return_thunk'
/home/arslan/trunk/bin/ld: hkdf.c:(.text+0x1ab): undefined reference to `__x86_return_thunk'
/home/arslan/trunk/bin/ld: hkdf.c:(.text+0x1c3): undefined reference to `__x86_return_thunk'
/home/arslan/trunk/bin/ld: /home/arslan/Documents/sgxsdk/sgxsdk/SampleCode/intel-sgx-ssl/Linux/sgx/../package/lib64///libsgx_tsgxssl_crypto.a(hkdf.o):hkdf.c:(.text+0x3f4): more undefined references to `__x86_return_thunk' follow
collect2: error: ld returned 1 exit status`

What is the purpose of `__x86_return_thunk' symbol and where is it supposed to come from? I am inclined to believe that this is a build configuration related issue. I was using openssl-1.1.1d, which I was able to build without SGX extensions. Please let me know if I am missing something.

**Comment by jinghe-INTC** [comment]
There were some changes for LVI mitigation. To build the code successfully, please:
1. Update the tool chain. You can refer to https://github.com/intel/intel-sgx-ssl/issues/51#issuecomment-613893605
2. Take the SGX Linux SDK 2.9 or higher version.

Please try and let me know if there are still any issues. 
Thanks.

**Comment by Arslan8** [comment]
Hi @jinghe-INTC,

Thanks for the response. I was actually using GNU assembler (GNU Binutils) 2.34.50.20200416, since I figured the option was introduced recently and that caused the "__x86_return_thunk" issue. However, my SGX SDK was version 2.8. Updating the SDK version as you recommended resolved the issue for me. 
I will close the issue but it'd be great if the SDK version requirements can be put in the main readme.  Thanks again.

Cheers,
Arslan
