### ISSUE TITLE
compile error with openssl-1.1.1g

### ISSUE THREAD

**Issue by mccoysc** [intel/intel-sgx-ssl#64]
error like the following picture:
![aqBHWIT8](https://user-images.githubusercontent.com/18025276/86079208-9259c580-bac2-11ea-9b12-dfdd79d75cf2.png)

**Comment by jinghe-INTC** [comment]
The latest master branch is prepared for the coming release of SGX 2.10, which will provide a updated tool set and be able to recognize the new options for mitigation. The source code of the tool chain is available [here](https://github.com/bminor/binutils-gdb). You can build it by yourself or wait until it is released with SGX 2.10.

And a temporary workaround is to build SGX SSL without mitigation configurations, by making the non-mitigation target only:
$ make sgxssl_no_mitigation

**Comment by jinghe-INTC** [comment]
Now that [SGX 2.10 for Linux ](https://github.com/intel/linux-sgx/releases/tag/sgx_2.10) is released today. You can follow the steps in its REAMDE to find the right tool set.

**Comment by jinghe-INTC** [comment]
Close it since no more response from the original reporter.
