### ISSUE TITLE
Parallel build is broken

### ISSUE THREAD

**Issue by jurobystricky** [intel/intel-sgx-ssl#65]
When building the libraries:
<pre> 
$ make all test SGX_MODE=HW 
</pre>

Everything works fine. 
However, running 
<pre>
 make all test SGX_MODE=HW -j 16
</pre>

Results in build errors, such as:
<pre>
tctype.cpp:32:10: fatal error: sgx_tsgxssl_t.h: No such file or directory
 #include "sgx_tsgxssl_t.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
</pre>

It seems to be 100% reproducible.

**Comment by jinghe-INTC** [comment]
Yes. It seems a bug for parallel building. I will fix it.

**Comment by jinghe-INTC** [comment]
Close it since no more response from the original reporter.
