### ISSUE TITLE
The build does not build in SIM mode

### ISSUE THREAD

**Issue by kladkogex** [intel/intel-sgx-ssl#67]
make SGX_MODE=SIM sgxssl_no_mitigation gives 

gcc  -I. -Icrypto/include -Iinclude -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -include/d/sgxwallet/intel-sgx-ssl/Linux/../openssl_source/bypass_to_sgxssl.h -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/d/sgxwallet/intel-sgx-ssl/Linux/../openssl_source/OpenSSL_install_dir_tmp/ssl\"" -DENGINESDIR="\"/d/sgxwallet/intel-sgx-ssl/Linux/../openssl_source/OpenSSL_install_dir_tmp/lib/engines-1.1\"" -DNDEBUG -D_FORTIFY_SOURCE=2 -DGETPID_IS_MEANINGLESS -MMD -MF crypto/rand/rand_lib.d.tmp -MT crypto/rand/rand_lib.o -c -o crypto/rand/rand_lib.o crypto/rand/rand_lib.c
crypto/rand/rand_lib.c:14:10: fatal error: crypto/rand.h: No such file or directory
 #include "crypto/rand.h"
          ^~~~~~~~~~~~~~~

**Comment by jinghe-INTC** [comment]
Are you sure it is OpenSSL 1.1.1g source code used for the build? The missing file should be located at include/crypto of OpenSSL source code, which was not available until 1.1.1e. 

And I don't think it was due to the simulation mode.  Please take SGX SDK 2.10 Linux and OpenSSL 1.1.1g for your project.

**Comment by jinghe-INTC** [comment]
Close it since no more response from the original reporter.
