### ISSUE TITLE
make all test failure

### ISSUE THREAD

**Issue by licc15** [intel/intel-sgx-ssl#68]
as: unrecognized option '-mlfence-after-load=yes'
Makefile:667: recipe for target 'crypto/aes/aes_cbc.o' failed
make[2]: *** [crypto/aes/aes_cbc.o] Error 1
make[2]: 离开目录“/opt/intel/sgxssl/openssl_source/openssl-1.1.1g”
Makefile:64: recipe for target '/opt/intel/sgxssl/Linux/sgx/../package/lib64//libsgx_tsgxssl_crypto.a' failed
make[1]: *** [/opt/intel/sgxssl/Linux/sgx/../package/lib64//libsgx_tsgxssl_crypto.a] Error 1
make[1]: 离开目录“/opt/intel/sgxssl/Linux/sgx”
Makefile:41: recipe for target 'sgxssl' failed
make: *** [sgxssl] Error 2

**Comment by jinghe-INTC** [comment]
The latest SGX SSL depends on the latest release of SGX SDK release  2.10 for Linux, with a mitigation tool set. You can checkout the code from https://github.com/intel/linux-sgx, and do  `./download_prebuilt.sh` to get the tools, and copy them to /usr/local/bin manually.

A related issue is https://github.com/intel/intel-sgx-ssl/issues/64.

**Comment by licc15** [comment]
Thank you very much. Your help solved my errors perfectly.

**Comment by jinghe-INTC** [comment]
Happy to help.
