### ISSUE TITLE
Illegal instruction when trying to run test app

### ISSUE THREAD

**Issue by MewtR** [intel/intel-sgx-ssl#71]
As the title says, anytime I try to run `make test SGX_MODE=SIM`, the test application crashes with an illegal instruction error.
I built sgx-ssl with SDK 2.11 and openssl 1.1.1g in simulation mode on Linux. I also tried downgrading to SDK 2.10 but had the same problem. I get the same error when trying to run other applications that use sgx-ssl as well.

Any advice would be appreciated.

Thanks

**Comment by jinghe-INTC** [comment]
I tried the same command with  SGXSDK 2.11 and openssl 1.1.1g on my development platform, with no problem found. My questions:
1. Does it also happen it hardware mode?
2. Are you using a platform without SGX capability?

Please provide the output of the command `lscpu | grep Flags`.

Thanks

**Comment by MewtR** [comment]
1. My hardware doesn't support sgx therefore I don't use hardware mode
2. See 1

Output: 
```
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good acc_power nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt topoext perfctr_nb bpext ptsc perfctr_llc cpb hw_pstate ssbd vmmcall bmi1 xsaveopt arat npt lbrv svm_lock nrip_save tsc_scale flushbyasid decodeassists pausefilter pfthreshold overflow_recov
```

**Comment by jinghe-INTC** [comment]
It was probably due to the instruction `rdrand`, which was required by OpenSSL 1.1.1g, not supported by your hardware. I don't have any platform of this kind to prove it. Can you try with original OpenSSL code?
```
tar xvf openssl-1.1.1g.tar.gz
cd openssl-1.1.1g/
./Configure linux-x86_64
make
test/asn1_internal_test
```
Thanks

**Comment by lzha101** [comment]
I suppose this requirement is not from the official OpenSSL. `rdrand` instruction is required when you execute an SGX enclave, even on Simulation mode. If you have a chance to debug the failed test on your platform, you may see the illegal instruction exception is happened in the SGX trusted library (sgx_trts) before you call OpenSSL code inside enclave.

**Comment by MewtR** [comment]
@jinghe-INTC 
The test seems to pass. Here is the output:
```
1..2
# INFO:  @ test/asn1_internal_test.c:44
# asn1 tbl_standard: Table order OK
ok 1 - test_tbl_standard
# INFO:  @ test/asn1_internal_test.c:97
# asn1 standard methods: Table order OK
ok 2 - test_standard_methods
```

@lzha101 
But it seems to me like `rdrand` is a requirement of sgx-ssl because I've been able to run other regular sgx applications in the past on the same machine. 

I know it's a longshot, but is there any workaround to get it to work on a machine without the `rdrand` instruction?

**Comment by lzha101** [comment]
Did you try the latest SGX SDK with SampleEnclave?  `rdrand` requirement has been introduced for a long time.  So I'm not sure why you can succeed to run other SGX applications.

To walk around this, you can refer to the patch attached in below link: 
https://github.com/intel/linux-sgx/issues/378

**Comment by MewtR** [comment]
Yes with the latest SDK I can run the SampleEnclave without any issues.
I have only started encountering this error when attempting to use ssl sgx.

**Comment by lzha101** [comment]
It's weird. I suggest you to build and install a debug version SDK, rebuild and debug the failed test to bring the backtrace here.

**Comment by jinghe-INTC** [comment]
Close it since no more response from the original reporter.
