### ISSUE TITLE
Build fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by lubaolalala** [intel/intel-sgx-ssl#73]
/usr/local/bin/ld:/intel-sgx-ssl/Linux/sgx/../package/lib64///libsgx_tsgxssl_crypto.a(threads_pthread.o): in function `CRYPTO_THREAD_lock_new':
threads_pthread.c:(.text+0x56): undefined reference to `pthread_rwlock_init'
/usr/local/bin/ld: /intel-sgx-ssl/Linux/sgx/../package/lib64///libsgx_tsgxssl_crypto.a(threads_pthread.o): in function `CRYPTO_THREAD_read_lock':
threads_pthread.c:(.text+0x95): undefined reference to `pthread_rwlock_rdlock'
/usr/local/bin/ld: /intel-sgx-ssl/Linux/sgx/../package/lib64///libsgx_tsgxssl_crypto.a(threads_pthread.o): in function `CRYPTO_THREAD_write_lock':
threads_pthread.c:(.text+0xb5): undefined reference to `pthread_rwlock_wrlock'
/usr/local/bin/ld: /intel-sgx-ssl/Linux/sgx/../package/lib64///libsgx_tsgxssl_crypto.a(threads_pthread.o): in function `CRYPTO_THREAD_unlock':
threads_pthread.c:(.text+0xd5): undefined reference to `pthread_rwlock_unlock'
/usr/local/bin/ld: /intel-sgx-ssl/Linux/sgx/../package/lib64///libsgx_tsgxssl_crypto.a(threads_pthread.o): in function `CRYPTO_THREAD_lock_free':
threads_pthread.c:(.text+0xfa): undefined reference to `pthread_rwlock_destroy'
collect2: error: ld returned 1 exit status
make[3]: *** [sgx_t.mk:167: TestEnclave.so] Error 1

**Comment by lubaolalala** [comment]
I run the command "make all test".

**Comment by jinghe-INTC** [comment]
Please provide the version number of the SGX SDK you are using. If possible please download https://download.01.org/intel-sgx/sgx-linux/2.12/distro/ubuntu20.04-server/sgx_linux_x64_sdk_2.12.100.3.bin and try again.

**Comment by lubaolalala** [comment]
I use sgx sdk 2.10.

**Comment by lubaolalala** [comment]
Is there some problems with sdk2.10?

**Comment by lzha101** [comment]
These pthread APIs are introduced in SGX SDK 2.11. So please update your SDK to 2.11 or later and retry.

**Comment by lubaolalala** [comment]
Thank you very much!

**Comment by jinghe-INTC** [comment]
I am closing the case since it looks solved. You can reopen it if necessary.
