### ISSUE TITLE
ssl library is not supported

### ISSUE THREAD

**Issue by yanlu14** [intel/intel-sgx-ssl#76]
The library only provides libsgx_tsgxssl_crypto.a to support cryptographic functions，and ssl library is not supported，application cannot set up an SSL conection with an an SGX enclave.

**Comment by jinghe-INTC** [comment]
SSL/TLS library is supported in branch [support_tls_openssl3](https://github.com/intel/intel-sgx-ssl/tree/support_tls_openssl3) as an option.
