### ISSUE TITLE
Build failed 

### ISSUE THREAD

**Issue by anand10717** [intel/intel-sgx-ssl#78]
Hello!
I am trying to build SGXSSL 2.13 with openssl-1.1.1i. 
Getting the following error while running "make all test"

`/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" util/shlib_wrap.sh.in > "util/shlib_wrap.sh"
chmod a+x util/shlib_wrap.sh
Warning: consider configuring with no-makedepend, because if
         target system doesn't have /usr/bin/perl,
         then make will fail...
make[2]: Leaving directory '/home/local/ZOHOCORP/anand-3985/Documents/Official/repo/intel-sgx-ssl-lin_2.13_1.1.1i/openssl_source/openssl-1.1.1i'
make[2]: Entering directory '/home/local/ZOHOCORP/anand-3985/Documents/Official/repo/intel-sgx-ssl-lin_2.13_1.1.1i/openssl_source/openssl-1.1.1i'
gcc  -I. -Iinclude -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -mfunction-return=thunk-extern -fcf-protection=none -Wa,-mlfence-after-load=yes -Wa,-mlfence-before-indirect-branch=memory -Wa,-mlfence-before-ret=shl -include/home/local/ZOHOCORP/anand-3985/Documents/Official/repo/intel-sgx-ssl-lin_2.13_1.1.1i/Linux/../openssl_source/bypass_to_sgxssl.h -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/home/local/ZOHOCORP/anand-3985/Documents/Official/repo/intel-sgx-ssl-lin_2.13_1.1.1i/Linux/../openssl_source/OpenSSL_install_dir_tmp/ssl\"" -DENGINESDIR="\"/home/local/ZOHOCORP/anand-3985/Documents/Official/repo/intel-sgx-ssl-lin_2.13_1.1.1i/Linux/../openssl_source/OpenSSL_install_dir_tmp/lib/engines-1.1\"" -DNDEBUG -D_FORTIFY_SOURCE=2 -DGETPID_IS_MEANINGLESS -MMD -MF crypto/aes/aes_cbc.d.tmp -MT crypto/aes/aes_cbc.o -c -o crypto/aes/aes_cbc.o crypto/aes/aes_cbc.c
as: unrecognized option '-mlfence-after-load=yes'
make[2]: *** [Makefile:667: crypto/aes/aes_cbc.o] Error 1
make[2]: Leaving directory '/home/local/ZOHOCORP/anand-3985/Documents/Official/repo/intel-sgx-ssl-lin_2.13_1.1.1i/openssl_source/openssl-1.1.1i'
make[1]: *** [Makefile:65: /home/local/ZOHOCORP/anand-3985/Documents/Official/repo/intel-sgx-ssl-lin_2.13_1.1.1i/Linux/sgx/../package/lib64//libsgx_tsgxssl_crypto.a] Error 1
make[1]: Leaving directory '/home/local/ZOHOCORP/anand-3985/Documents/Official/repo/intel-sgx-ssl-lin_2.13_1.1.1i/Linux/sgx'
make: *** [Makefile:42: sgxssl] Error 2
`
OS : Ubuntu 20.04.
SGX SDK,PSW and Drivers are already installed.

**Comment by johnvenn** [comment]
hi, the reason of the error is the your build environment requires LVI mitigation toolset. Please refer to intel-sgx repo readme: https://github.com/intel/linux-sgx 

the following instruction: 
Copy the mitigation tools corresponding to current OS distribution from external/toolset/{current_distr} to /usr/local/bin and make sure they have execute permission:
  $ sudo cp external/toolset/{current_distr}/{as,ld,ld.gold,objdump} /usr/local/bin
  $ which as ld ld.gold objdump

**Comment by jinghe-INTC** [comment]
It is recommended to take LVI mitigation toolset to build all 3 configurations of SGX SSL as mentioned above. But you can also try
$ make sgxssl_no_mitigation test
to build non-LVI mitigation configuration, only if you are sure that LVI mitigation is not necessary for your project.

**Comment by jinghe-INTC** [comment]
I have added a quick check in the make file. In case you haven't update the toolset yet, it will print the below message at the beginning of the build:
```
$ make 
Please follow the instruction at https://github.com/intel/linux-sgx/blob/master/README.md#build-the-intelr-sgx-sdk-and-intelr-sgx-psw-package to install "mitigation tools".
```

**Comment by jinghe-INTC** [comment]
Close it since suggestion provided and build script enhanced. Feel free to reopen or open new issues.
