### ISSUE TITLE
Conflicting defintions with tlibc

### ISSUE THREAD

**Issue by Arslan8** [intel/intel-sgx-ssl#79]
While using intel sgx ssl, i encountered the following error:
```
In file included from /home/arslan/Documents/sgxsdk/sgxsdk/SampleCode/ssl2/intel-sgx-ssl/Linux/sgx/../package/include/openssl/asn1.h:13:0,
                 from /home/arslan/Documents/sgxsdk/sgxsdk/SampleCode/ssl2/intel-sgx-ssl/Linux/sgx/../package/include/openssl/ec.h:17,
                 from enclave/TestEnclave.cpp:40:
/home/arslan/Documents/sgxsdk/sgxsdk/include/tlibc/time.h:75:8: error: redefinition of ‘struct tm’
 struct tm {
        ^~
In file included from enclave/TestEnclave_t.h:9:0,
                 from enclave/TestEnclave.cpp:37:
/home/arslan/Documents/sgxsdk/sgxsdk/SampleCode/ssl2/intel-sgx-ssl/Linux/sgx/test_app/enclave/../../libsgx_tsgxssl/tdefines.h:42:8: note: previous definition of ‘struct tm’
 struct tm
        ^~
```
Looking at the definition, the last two fields in these definitions are conflicting.
```
struct tm {
    int tm_sec;     /* seconds after the minute [0-60] */
    int tm_min;     /* minutes after the hour [0-59] */
    int tm_hour;    /* hours since midnight [0-23] */
    int tm_mday;    /* day of the month [1-31] */
    int tm_mon;     /* months since January [0-11] */
    int tm_year;    /* years since 1900 */
    int tm_wday;    /* days since Sunday [0-6] */
    int tm_yday;    /* days since January 1 [0-365] */
    int tm_isdst;   /* Daylight Saving Time flag */
    /* FIXME: naming issue exists on Fedora/Ubuntu */
    long tm_gmtoff; /* offset from UTC in seconds */
    char *tm_zone;  /* timezone abbreviation */
};
```
```
struct tm^M
{^M
  int tm_sec;^M
  int tm_min;^M
  int tm_hour;^M
  int tm_mday;^M
  int tm_mon;^M
  int tm_year;^M
  int tm_wday;^M
  int tm_yday;^M
  int tm_isdst;^M
^M
  long int tm_gmtoff;^M
  const char *tm_zone;^M
};
```

I am using lin_2.9.1_1.1.1d version.

**Comment by johnvenn** [comment]
you want to use trusted time inside enclave?

did you try build your enclave by adding an option "-D_TIM_DEFINED" as in tlibc/time.h to avoid the compilation conflict?

**Comment by johnvenn** [comment]
checked TestEnclave.cpp in the test folder, not sure why here you included "tdfines.h", this header file is used for building sgx_tsgxssl library, it should not be used in enclave apps. For enclave apps that using sgxssl, C standard functions are from tlibc headers in Intel SGXSDK as usual. Please check.

**Comment by Arslan8** [comment]
It is the demo test app that comes with the repo, I included another edl for a separate library, however , the original error was a conflict in:
```
In file included from enclave/../../libsgx_tsgxssl/tcommon.h:40:0,
                 from enclave/tests/missing_funcs.c:38:
enclave/../../libsgx_tsgxssl/tdefines.h:108:13: error: conflicting types for ‘pthread_once_t’
 typedef int pthread_once_t;
             ^~~~~~~~~~~~~~
In file included from enclave/TestEnclave_t.h:9:0,
                 from enclave/tests/missing_funcs.c:37:
/home/arslan/Documents/sgxsdk/sgxsdk/include/tlibc/pthread.h:73:2: note: previous declaration of ‘pthread_once_t’ was here
 }pthread_once_t;
  ^~~~~~~~~~~~~~
  
```
As you can see that enclave/tests/missing_funcs.c is including "../../libsgx_tsgxssl/tcommon.h" which in turn does pull "tdefines.h"...Anyhow to make it work I decided to pull more definitions from tdefines instead of going in the other direction... So, to get rid of this error I included tdefines.h, so instead of tlibc it would pull the sgx_tsgxssl library one. These are again different. Should I not include pthread.h in my edl(the new one I am adding in the demo?)

**Comment by johnvenn** [comment]
not sure what is your scenario, but I think the error is you must have included the 2 header files in the same source. tdefines.h and headers in tlibc have some in common, including them in the same source may cause def conflict.

**Comment by lzha101** [comment]
> Should I not include pthread.h in my edl(the new one I am adding in the demo?)

Is there any specific reason you need to include pthread.h in the edl? I'm not saying you should not add. But just want to know if you can walkaround this build failure by not adding it to edl.

And I suppose we indeed need to cleanup the header files in sgxssl and utilize the definition in SGXSDK instead,, since sgxssl depends on SGXSDK. This could reduce type conflicts errors.

**Comment by Arslan8** [comment]
@johnvenn yes that is what is causing the conflict...but I am not sure if there should've been a conflict...

@lzha101  I have an application I am trying to run inside an enclave that requires the following pthread apis:
```
pthread_self
pthread_attr_init
pthread_attr_destroy
pthread_key_create
pthread_getspecific
pthread_setspecific
```
Right now I emulate these APIs in the other EDL i mentioned and it works with other SGX projects, however with intel-sgx-ssl i am seeing these clashes. The problem is that the clash is not within my EDL and tlibc definition. But tdefins and tlibc, I can work around this problem locally by modifying my EDL, but I am not sure if that's the best solution here.

**Comment by johnvenn** [comment]
part of those pthread functions in intel-sgx-ssl is implemented in Linux/sgx/libsgx_tsgxssl/tpthread.cpp and renamed as sgxssl_pthread*... you may use those functions in this way. But for attr_init/attr_destroy, the 2 functions are not supported inside enclave.

**Comment by jinghe-INTC** [comment]
The redefinitions of `tm`, `pthread_once_t` have been fixed in the latest commit.

**Comment by jinghe-INTC** [comment]
Conflicts of pthread_self and pthread_equal have been solved in https://github.com/intel/intel-sgx-ssl/pull/89

**Comment by Arslan8** [comment]
Hi @jinghe-INTC I bypassed the issue using local definitions for my applications..if you've done the testing on your side feel free to close the issue...

**Comment by jinghe-INTC** [comment]
> Hi @jinghe-INTC I bypassed the issue using local definitions for my applications..if you've done the testing on your side feel free to close the issue...

Thanks. It seems more SGX SSL local definitions need to be replaced by that from SGX SDK. I would keep this issue for tracking.

**Comment by jinghe-INTC** [comment]
Close it now.
