### ISSUE TITLE
error C2169: 'lrintl': intrinsic function, cannot  be defined

### ISSUE THREAD

**Issue by marektopolewski** [intel/intel-sgx-ssl#86]
Hi,

I'm trying to build on Windows and while the Debug build succeeds, the Release one fails with:

```
C:\Program Files (x86)\Intel\IntelSGXSDK\include\tlibc\math.h(503,9): error C2169: 'lrintl': intrinsic function, cannot be defined [C:\Intel\intel-sgx-ssl\Windows\sgx\libsgx_tsgxssl\libsgx_tsgxssl.vcxproj]
 ```
Full log: [release_build.log](https://github.com/intel/intel-sgx-ssl/files/6391183/release_build.log)

`build_all.cmd`:
```
"Validating Prerequisites (7z, perl, nasm)"
"Building SGXSSL with: openssl-1.1.1k  28/04/2021 12:22:40.06 to 2.11.100.3_1.1.1k"
"Building x64_debug  28/04/2021 12:22:40.06"
"Successfully built x64_debug  28/04/2021 12:25:16.36"
"Building x64_release  28/04/2021 12:26:02.12"
```

Can anyone help me out?

**Comment by jinghe-INTC** [comment]
This is actually a SGX Windows SDK problem,  only found with the VS2019 after some recent update. 

Before we update math.h in the next release, you can manually change the Line502-503 to:
```
#if  _MSC_FULL_VER >= 192829910
    long int _TLIBC_CDECL_ lrintl(long double x);
#else
    inline long int _TLIBC_CDECL_ lrintl(long double x)
        { return (lrint((double)x));}
#endif 
```

**Comment by xxu36** [comment]
@marektopolewski Yes, you can work around this issue using @jinghe-INTC 's proposal. Seems VS2019 implements new intrinsic functions, including `lrintl`, so we do not need the definition any more.

**Comment by marektopolewski** [comment]
The SDK fix was sufficient btw so thanks and feel free to close 👍

**Comment by jinghe-INTC** [comment]
You're welcome.
