### ISSUE TITLE
Using SSL APIs

### ISSUE THREAD

**Issue by byteystring** [intel/intel-sgx-ssl#9]
I am writing an application that needs to use APIs from OpenSSL like SSL_write/SSL_read.
However, this doesn't work with the default build (compiler returns  error: undefined reference to SSl_write/SSL_read). Is openssl/ssl binary not included in the building process?

**Comment by akryeem-INTC** [comment]
That's right. Currently the library only support crypto OpenSSL APIs, and it doesn't include the TLS(SSL) library.

> The Intel® Software Guard Extensions SSL (Intel® SGX SSL) **cryptographic** library is intended to provide **cryptographic services** for Intel® Software Guard Extensions (SGX) enclave applications.
