### ISSUE TITLE
When using intel-sgx-ssl, running app illegal instruction error on cpuid 

### ISSUE THREAD

**Issue by YangLiang3** [intel/intel-sgx-ssl#94]
According to sgx-gdb's steps, **the bold part** will call libc and raise an error, then exit. It should be in libsgx_urts.so to handle exeception. But I don't know why it will enter into libc. Could you please give me some suggestion?

Breakpoint 1, OPENSSL_ia32_cpuid () at crypto/x86_64cpuid.s:44
44              movq    %rbx,%r8
(gdb) c
Continuing.

Program received signal SIGILL, Illegal instruction.
OPENSSL_ia32_cpuid () at crypto/x86_64cpuid.s:49
49              cpuid
(gdb) c
Continuing.

Breakpoint 2, 0x00007fffe8059794 in internal_handle_exception ()
(gdb) c
Continuing.

Program received signal SIGILL, Illegal instruction.
OPENSSL_ia32_cpuid () at crypto/x86_64cpuid.s:49
49              cpuid
(gdb) c
Continuing.

**Program received signal SIGILL, Illegal instruction.
0x00007ffff755337f in raise () from /usr/lib64/libc.so.6
(gdb) c
Continuing.**

Program terminated with signal SIGILL, Illegal instruction.
The program no longer exists.
(gdb) bt
No stack.
(gdb) quit

**Comment by lzha101** [comment]
Is **the bold part** really caused by CPUID? Could you try `bt` to get the backtrace before continue?

**Comment by YangLiang3** [comment]
@lzha101  please refer to the following, it's in OPENSSL_ia32_cpuid
Breakpoint 1, OPENSSL_ia32_cpuid () at crypto/x86_64cpuid.s:44
44              movq    %rbx,%r8
(gdb) n
47              xorl    %eax,%eax
(gdb) n
48              movq    %rax,8(%rdi)
(gdb) n
49              cpuid
(gdb) s

Program received signal SIGILL, Illegal instruction.
OPENSSL_ia32_cpuid () at crypto/x86_64cpuid.s:49
49              cpuid
(gdb) s
0x00007ffff7fd0670 in sig_handler(int, siginfo_t*, void*) () from /usr/lib64/libsgx_urts.so
(gdb) s
Single stepping until exit from function _Z11sig_handleriP9siginfo_tPv,
which has no line number information.
0x00007fffe8059790 in internal_handle_exception ()
(gdb) bt
#0  0x00007fffe8059790 in internal_handle_exception ()
#1  0x00007fffe80a6a19 in OPENSSL_ia32_cpuid () at crypto/x86_64cpuid.s:48
#2  0x0000000000000000 in ?? ()
(gdb) s
Single stepping until exit from function internal_handle_exception,
which has no line number information.

Program received signal SIGILL, Illegal instruction.
OPENSSL_ia32_cpuid () at crypto/x86_64cpuid.s:49
49              cpuid
(gdb) s
0x00007ffff7fd0670 in sig_handler(int, siginfo_t*, void*) () from /usr/lib64/libsgx_urts.so
(gdb) bt
#0  0x00007ffff7fd0670 in sig_handler(int, siginfo_t*, void*) () from /usr/lib64/libsgx_urts.so
#1  <signal handler called>
#2  0x00007ffff7fc8b97 in __morestack () from /usr/lib64/libsgx_urts.so
#3  0x00007ffff7fcbb7a in CEnclave::ecall(int, void const*, void*, bool) () from /usr/lib64/libsgx_urts.so
#4  0x00007ffff7fcda81 in _sgx_ecall(unsigned long, int, void const*, void*, bool) () from /usr/lib64/libsgx_urts.so
#5  0x00000000004032a7 in ecall_etls_server_startup (eid=2, retval=0x7fffffffdd50, enclave_id=2, log_level=ENCLAVE_TLS_LOG_LEVEL_INFO, attester_type=0x405116 "", verifier_type=0x405116 "", tls_type=0x7fffffffe36c "openssl", crypto_type=0x7fffffffe377 "openssl", flags=4294967296,
    s_ip=16777343, s_port=53764) at  build/samples/enclave-tls-server/sgx_stub_u.c:573
#6  0x00000000004025d3 in enclave_tls_server_startup (log_level=ENCLAVE_TLS_LOG_LEVEL_INFO, attester_type=0x405116 "", verifier_type=0x405116 "", tls_type=0x7fffffffe36c "openssl", crypto_type=0x7fffffffe377 "openssl", mutual=false, debug_enclave=true, ip=0x405117 "127.0.0.1",
    port=1234) at samples/enclave-tls-server/server.c:119
#7  0x000000000040291c in main (argc=5, argv=0x7fffffffe048) at samples/enclave-tls-server/server.c:354
(gdb) s
Single stepping until exit from function _Z11sig_handleriP9siginfo_tPv,
which has no line number information.

Program received signal SIGILL, Illegal instruction.
0x00007ffff755337f in raise () from /usr/lib64/libc.so.6
(gdb) bt
#0  0x00007ffff755337f in raise () from /usr/lib64/libc.so.6
#1  0x00007ffff7fd0832 in sig_handler(int, siginfo_t*, void*) () from /usr/lib64/libsgx_urts.so
#2  <signal handler called>
#3  0x00007ffff7fc8b97 in __morestack () from /usr/lib64/libsgx_urts.so
#4  0x00007ffff7fcbb7a in CEnclave::ecall(int, void const*, void*, bool) () from /usr/lib64/libsgx_urts.so
#5  0x00007ffff7fcda81 in _sgx_ecall(unsigned long, int, void const*, void*, bool) () from /usr/lib64/libsgx_urts.so
#6  0x00000000004032a7 in ecall_etls_server_startup (eid=2, retval=0x7fffffffdd50, enclave_id=2, log_level=ENCLAVE_TLS_LOG_LEVEL_INFO, attester_type=0x405116 "", verifier_type=0x405116 "", tls_type=0x7fffffffe36c "openssl", crypto_type=0x7fffffffe377 "openssl", flags=4294967296,
    s_ip=16777343, s_port=53764) at build/samples/enclave-tls-server/sgx_stub_u.c:573
#7  0x00000000004025d3 in enclave_tls_server_startup (log_level=ENCLAVE_TLS_LOG_LEVEL_INFO, attester_type=0x405116 "", verifier_type=0x405116 "", tls_type=0x7fffffffe36c "openssl", crypto_type=0x7fffffffe377 "openssl", mutual=false, debug_enclave=true, ip=0x405117 "127.0.0.1",
    port=1234) at samples/enclave-tls-server/server.c:119
#8  0x000000000040291c in main (argc=5, argv=0x7fffffffe048) at samples/enclave-tls-server/server.c:354

**Comment by lzha101** [comment]
Seems the CPUID is not handled correctly in your project and it eventually crashed the app. Suggest to build a debug version SGX SDK to get more debug info.

**Comment by YangLiang3** [comment]
@lzha101  Many thanks for support. Following your sugestion , after debug, it's releated to enclave compiler options.
