### ISSUE TITLE
tstdio.cpp, tunistd.cpp, tcommon.h files are dos format, maintainer can you format it?

### ISSUE THREAD

**Issue by YangLiang3** [intel/intel-sgx-ssl#96]
For example: 
--- a/Linux/sgx/libsgx_tsgxssl/tstdio.cpp
+++ b/Linux/sgx/libsgx_tsgxssl/tstdio.cpp
@@ -1,55 +1,273 @@
-/*^M
- * Copyright (C) 2011-2017 Intel Corporation. All rights reserved.^M
- *^M
- * Redistribution and use in source and binary forms, with or without^M
- * modification, are permitted provided that the following conditions^M
- * are met:^M
- *^M
- *   * Redistributions of source code must retain the above copyright^M
- *     notice, this list of conditions and the following disclaimer.^M
- *   * Redistributions in binary form must reproduce the above copyright^M
- *     notice, this list of conditions and the following disclaimer in^M
- *     the documentation and/or other materials provided with the^M
- *     distribution.^M
- *   * Neither the name of Intel Corporation nor the names of its^M
- *     contributors may be used to endorse or promote products derived^M
- *     from this software without specific prior written permission.^M
- *^M
- * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS^M
- * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT^M
- * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR^M
- * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT^M
- * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,^M
- * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT^M
- * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,^M
- * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY^M
- * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT^M
- * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE^M
- * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.^M
- *^M
- */^M
-^M
-#include <stdio.h>^M
-#include "tcommon.h"^M
-#include "sgx_tsgxssl_t.h"^M
-#include "tSgxSSL_api.h"^M
-^M
-extern PRINT_TO_STDOUT_STDERR_CB s_print_cb;^M
-^M
-extern "C" {^M
-^M
-int sgx_print(const char *format, ...)^M
-{^M
-       if (s_print_cb != NULL) {^M
-               va_list vl;^M
-               va_start(vl, format);^M
-               int res = s_print_cb(STREAM_STDOUT, format, vl);^M
-               va_end(vl);^M
-^M
-               return res;^M
-       }^M
-       ^M
-       return 0;^M
-}^M
-^M

**Comment by jinghe-INTC** [comment]
If possible, please try the fork branch https://github.com/jinghe-INTC/intel-sgx-ssl/tree/update_file_format_for_linux_source

**Comment by jinghe-INTC** [comment]
File change has been merge to master branch. Please verify it.

**Comment by YangLiang3** [comment]
thanks
