### ISSUE TITLE
How to push code to intel-sgx-ssl

### ISSUE THREAD

**Issue by xiaonan-INTC** [intel/intel-sgx-ssl#99]
hello guys,

I am from Intel SGX team, and I want to add some code to intel-sgxssl, but when I try to do git push, 

remote: Permission to intel/intel-sgx-ssl.git denied to xiaonan-INTC.
fatal: unable to access 'https://github.com/intel/intel-sgx-ssl.git/': The requested URL returned error: 403

Who can help solve this issue for me? Thanks!

**Comment by jinghe-INTC** [comment]
You can apply to be a contributor of the project. But do pull request from a fork is recommended.

**Comment by xiaonan-INTC** [comment]
Solved, thanks Jing.
